/* ===========================================================
   Albion Meta - kills counted from the Albion API
   -----------------------------------------------------------
   Written by collect-winrates.py, do not edit by hand.

   "kills" counts how often the first weapon beat the second in
   a fight that looked like a 2v2: one assist, both players
   under 1350 item power, both on a weapon this site lists.

   "duos" is the same fights read as a whole: a pair beating a
   pair, worked out by waiting for both of the losing side to
   die in the same battle. That is the only way to know which
   dps died next to a healer, the event itself never says.

   All three Albion worlds are read, Americas, Europe and Asia,
   and counted together. "regions" is only there to show how
   much each one contributed.

   The API cannot say a kill happened in a hellgate, so this is
   the shape of the fight, not a hellgate flag. Run the script
   often, it only ever sees the last half hour of kills.
   =========================================================== */

window.ALBION_WINRATES = {
 "updated": "2026-09-15T02:54:47+00:00",
 "eventsSeen": 45496,
 "qualifying": 2720,
 "duoFights": 664,
 "runs": 43,
 "regions": {
  "americas": {
   "events": 22704,
   "kills": 1290,
   "lastSeen": "2026-09-15T02:47:33.713878100Z"
  },
  "europe": {
   "events": 16826,
   "kills": 1169,
   "lastSeen": "2026-09-15T02:49:19.714830100Z"
  },
  "asia": {
   "events": 5966,
   "kills": 261,
   "lastSeen": "2026-09-15T02:48:35.954349700Z"
  }
 },
 "kills": {
  "Carrioncaller": {
   "Dagger": 1,
   "Holy Staff": 29,
   "Grailseeker": 1,
   "Blight Staff": 1,
   "Bloodletter": 3,
   "Crossbow": 2,
   "Brawler Gloves": 2,
   "Whispering Bow": 1,
   "Great Holy Staff": 5,
   "Carving Sword": 4,
   "Ursine Maulers": 1,
   "Infernal Scythe": 1,
   "Cursed Staff": 1,
   "Heavy Crossbow": 4,
   "Bear Paws": 1,
   "Dagger Pair": 9,
   "Claymore": 4,
   "Carrioncaller": 2,
   "Longbow": 2,
   "Demonic Staff": 3,
   "Hellspawn Staff": 3,
   "Prowling Staff": 4,
   "Broadsword": 1,
   "Soulscythe": 1,
   "Fists of Avalon": 2,
   "Arclight Blasters": 2,
   "Realmbreaker": 1
  },
  "Deathgivers": {
   "Warbow": 2,
   "Dagger Pair": 3,
   "Cursed Staff": 5,
   "Blight Staff": 1,
   "Greataxe": 4,
   "Bow of Badon": 4,
   "Battleaxe": 8,
   "Claymore": 4,
   "Holy Staff": 11,
   "Carrioncaller": 2,
   "Brawler Gloves": 5,
   "Whispering Bow": 1,
   "Great Fire Staff": 1,
   "Broadsword": 1,
   "Bear Paws": 1,
   "Crossbow": 1,
   "Hellspawn Staff": 1,
   "Staff of Balance": 1,
   "Blazing Staff": 2,
   "Dagger": 1,
   "Carving Sword": 4,
   "Longbow": 3,
   "Lifecurse Staff": 1,
   "Bloodletter": 1,
   "Heavy Crossbow": 4,
   "Mistpiercer": 1,
   "Ursine Maulers": 1,
   "Heron Spear": 3
  },
  "Dagger Pair": {
   "Holy Staff": 55,
   "Dagger": 1,
   "Longbow": 8,
   "Carrioncaller": 5,
   "Claymore": 13,
   "Bear Paws": 7,
   "Battleaxe": 10,
   "Heavy Crossbow": 10,
   "Hallowfall": 2,
   "Dagger Pair": 12,
   "Rotcaller Staff": 2,
   "Hellspawn Staff": 2,
   "Blight Staff": 3,
   "Great Fire Staff": 2,
   "Bloodletter": 2,
   "Crossbow": 2,
   "Ironroot Staff": 1,
   "Deathgivers": 3,
   "Greataxe": 1,
   "Realmbreaker": 1,
   "Bow of Badon": 4,
   "Wildfire Staff": 2,
   "Infernal Scythe": 1,
   "Energy Shaper": 2,
   "Redemption Staff": 1,
   "Great Holy Staff": 2,
   "Lifecurse Staff": 2,
   "Carving Sword": 3,
   "Staff of Balance": 3,
   "Glacial Staff": 3,
   "Demonic Staff": 4,
   "Soulscythe": 2,
   "Bedrock Mace": 1,
   "Cursed Staff": 5,
   "Whispering Bow": 1,
   "Warbow": 2,
   "Divine Staff": 1,
   "Brawler Gloves": 8,
   "Broadsword": 1,
   "Grailseeker": 2,
   "Kingmaker": 1,
   "Tombhammer": 4,
   "Ursine Maulers": 1,
   "Heron Spear": 1,
   "Arclight Blasters": 1
  },
  "Demonic Staff": {
   "Blazing Staff": 2,
   "Claymore": 20,
   "Dagger": 5,
   "Holy Staff": 54,
   "Carrioncaller": 2,
   "Heavy Crossbow": 16,
   "Dagger Pair": 11,
   "Glacial Staff": 3,
   "Great Holy Staff": 1,
   "Prowling Staff": 2,
   "Warbow": 1,
   "Battleaxe": 3,
   "Brawler Gloves": 9,
   "Longbow": 2,
   "Soulscythe": 2,
   "Great Fire Staff": 1,
   "Greataxe": 1,
   "Broadsword": 1,
   "Deathgivers": 2,
   "Bow of Badon": 4,
   "Twin Slayers": 2,
   "Wildfire Staff": 1,
   "Staff of Balance": 8,
   "Carving Sword": 2,
   "Arclight Blasters": 2,
   "Fists of Avalon": 2,
   "Demonic Staff": 4,
   "Pike": 2,
   "Grailseeker": 3,
   "Hellfire Hands": 2,
   "Hellspawn Staff": 1
  },
  "Claymore": {
   "Dagger": 2,
   "Grailseeker": 7,
   "Bloodletter": 4,
   "Heavy Crossbow": 35,
   "Holy Staff": 110,
   "Divine Staff": 4,
   "Claymore": 18,
   "Great Holy Staff": 3,
   "Bow of Badon": 6,
   "Dagger Pair": 21,
   "Cursed Staff": 10,
   "Blight Staff": 5,
   "Demonic Staff": 16,
   "Battleaxe": 14,
   "Hellfire Hands": 10,
   "Greataxe": 5,
   "Tombhammer": 2,
   "Lifecurse Staff": 2,
   "Crossbow": 6,
   "Whispering Bow": 4,
   "Daybreaker": 1,
   "Wildfire Staff": 4,
   "Forcepulse Bracers": 2,
   "Bedrock Mace": 1,
   "Brawler Gloves": 10,
   "Longbow": 6,
   "Warbow": 14,
   "Deathgivers": 4,
   "Hellspawn Staff": 9,
   "Crystal Reaper": 1,
   "Carving Sword": 5,
   "Ironroot Staff": 4,
   "Carrioncaller": 5,
   "Hallowfall": 1,
   "Fists of Avalon": 1,
   "Staff of Balance": 4,
   "Glacial Staff": 3,
   "Soulscythe": 1,
   "Great Fire Staff": 5,
   "Heron Spear": 2,
   "Glaive": 2,
   "Prowling Staff": 2,
   "Realmbreaker": 1,
   "Energy Shaper": 2,
   "Arclight Blasters": 3,
   "Rotcaller Staff": 1,
   "Broadsword": 2,
   "Spirithunter": 1,
   "Infernal Scythe": 1,
   "Kingmaker": 1,
   "Mistpiercer": 1,
   "Redemption Staff": 1,
   "Blazing Staff": 1,
   "Occult Staff": 1
  },
  "Whispering Bow": {
   "Bow of Badon": 1,
   "Cursed Staff": 1,
   "Carrioncaller": 1,
   "Bloodletter": 2,
   "Warbow": 3,
   "Spirithunter": 1,
   "Claymore": 1,
   "Holy Staff": 1,
   "Crossbow": 1,
   "Mistpiercer": 1,
   "Lifecurse Staff": 2,
   "Longbow": 3,
   "Crystal Reaper": 1,
   "Infernal Scythe": 1,
   "Broadsword": 2,
   "Bear Paws": 1,
   "Battleaxe": 2,
   "Kingmaker": 1,
   "Brawler Gloves": 1,
   "Carving Sword": 1,
   "Glacial Staff": 1
  },
  "Arclight Blasters": {
   "Demonic Staff": 4,
   "Holy Staff": 32,
   "Hellspawn Staff": 2,
   "Bow of Badon": 12,
   "Energy Shaper": 2,
   "Carrioncaller": 3,
   "Wildfire Staff": 2,
   "Claymore": 9,
   "Arclight Blasters": 6,
   "Great Holy Staff": 5,
   "Heavy Crossbow": 5,
   "Longbow": 5,
   "Realmbreaker": 1,
   "Battleaxe": 6,
   "Greataxe": 3,
   "Ironroot Staff": 3,
   "Deathgivers": 3,
   "Hallowfall": 4,
   "Bloodletter": 1,
   "Mistpiercer": 2,
   "Warbow": 3,
   "Blazing Staff": 2,
   "Bear Paws": 3,
   "Grailseeker": 1,
   "Blight Staff": 1,
   "Carving Sword": 1,
   "Heron Spear": 3,
   "Forcepulse Bracers": 1,
   "Glacial Staff": 1,
   "Tombhammer": 1,
   "Rotcaller Staff": 1,
   "Brawler Gloves": 3,
   "Kingmaker": 1,
   "Dagger Pair": 1
  },
  "Greataxe": {
   "Mistpiercer": 2,
   "Battleaxe": 9,
   "Broadsword": 1,
   "Lifecurse Staff": 1,
   "Hallowfall": 3,
   "Bloodletter": 2,
   "Bow of Badon": 3,
   "Great Fire Staff": 2,
   "Blight Staff": 1,
   "Crystal Reaper": 1,
   "Spirithunter": 1,
   "Soulscythe": 1,
   "Hellspawn Staff": 1,
   "Holy Staff": 6,
   "Cursed Staff": 3,
   "Pike": 1,
   "Realmbreaker": 1,
   "Deathgivers": 1,
   "Longbow": 3,
   "Warbow": 2,
   "Redemption Staff": 3,
   "Staff of Balance": 1,
   "Glacial Staff": 2,
   "Fists of Avalon": 1,
   "Dagger": 1,
   "Crossbow": 1,
   "Greataxe": 2,
   "Carrioncaller": 1,
   "Bear Paws": 2,
   "Dagger Pair": 5,
   "Whispering Bow": 2,
   "Heavy Crossbow": 2,
   "Claymore": 1,
   "Infernal Scythe": 1,
   "Grailseeker": 1,
   "Carving Sword": 2,
   "Brawler Gloves": 1
  },
  "Forcepulse Bracers": {
   "Arclight Blasters": 1,
   "Holy Staff": 1,
   "Crystal Reaper": 2,
   "Longbow": 1
  },
  "Heavy Crossbow": {
   "Carrioncaller": 5,
   "Holy Staff": 70,
   "Grailseeker": 1,
   "Dagger": 2,
   "Bear Paws": 7,
   "Longbow": 3,
   "Greataxe": 8,
   "Heavy Crossbow": 22,
   "Dagger Pair": 8,
   "Warbow": 8,
   "Deathgivers": 6,
   "Claymore": 18,
   "Staff of Balance": 4,
   "Whispering Bow": 4,
   "Fists of Avalon": 2,
   "Broadsword": 2,
   "Cursed Staff": 4,
   "Hellspawn Staff": 7,
   "Brawler Gloves": 6,
   "Great Fire Staff": 2,
   "Pike": 2,
   "Kingmaker": 1,
   "Hallowfall": 1,
   "Great Holy Staff": 2,
   "Carving Sword": 2,
   "Energy Shaper": 1,
   "Hellfire Hands": 6,
   "Tombhammer": 5,
   "Bloodletter": 3,
   "Black Monk Stave": 1,
   "Demonic Staff": 2,
   "Glacial Staff": 2,
   "Battleaxe": 3,
   "Prowling Staff": 1,
   "Glaive": 2,
   "Blazing Staff": 1,
   "Crystal Reaper": 1,
   "Heron Spear": 1,
   "Mistpiercer": 1,
   "Crossbow": 1,
   "Realmbreaker": 1
  },
  "Warbow": {
   "Battleaxe": 2,
   "Cursed Staff": 6,
   "Claymore": 3,
   "Longbow": 4,
   "Holy Staff": 6,
   "Lifecurse Staff": 2,
   "Twin Slayers": 1,
   "Hellfire Hands": 2,
   "Heavy Crossbow": 7,
   "Bow of Badon": 8,
   "Bear Paws": 3,
   "Dawnsong": 1,
   "Mistpiercer": 3,
   "Warbow": 3,
   "Broadsword": 2,
   "Grailseeker": 3,
   "Deathgivers": 3,
   "Carving Sword": 1,
   "Demonic Staff": 1,
   "Blight Staff": 1,
   "Prowling Staff": 1,
   "Dagger Pair": 7,
   "Greataxe": 1,
   "Great Holy Staff": 1,
   "Ursine Maulers": 1,
   "Kingmaker": 2,
   "Fists of Avalon": 1,
   "Hellspawn Staff": 1,
   "Crystal Reaper": 1
  },
  "Battleaxe": {
   "Dagger Pair": 11,
   "Cursed Staff": 16,
   "Pike": 2,
   "Battleaxe": 16,
   "Dagger": 1,
   "Greataxe": 5,
   "Warbow": 4,
   "Longbow": 7,
   "Bloodletter": 7,
   "Crossbow": 5,
   "Hellfire Hands": 2,
   "Bow of Badon": 6,
   "Permafrost Prism": 2,
   "Great Fire Staff": 3,
   "Blight Staff": 2,
   "Bear Paws": 5,
   "Mistpiercer": 1,
   "Wildfire Staff": 4,
   "Ursine Maulers": 1,
   "Realmbreaker": 1,
   "Tombhammer": 3,
   "Holy Staff": 26,
   "Ironroot Staff": 1,
   "Heron Spear": 1,
   "Carving Sword": 4,
   "Crystal Reaper": 2,
   "Claymore": 6,
   "Heavy Crossbow": 5,
   "Deathgivers": 6,
   "Hallowfall": 1,
   "Kingmaker": 2,
   "Infernal Scythe": 1,
   "Spirithunter": 1,
   "Hellspawn Staff": 1,
   "Black Monk Stave": 2,
   "Glacial Staff": 2,
   "Whispering Bow": 2,
   "Arclight Blasters": 1,
   "Hoarfrost Staff": 1,
   "Divine Staff": 1,
   "Broadsword": 1,
   "Fists of Avalon": 1,
   "Soulscythe": 1,
   "Carrioncaller": 1,
   "Twin Slayers": 1,
   "Brawler Gloves": 2,
   "Prowling Staff": 1,
   "Icicle Staff": 1
  },
  "Dawnsong": {
   "Holy Staff": 2,
   "Energy Shaper": 1,
   "Crossbow": 1,
   "Dawnsong": 1,
   "Greataxe": 1
  },
  "Bow of Badon": {
   "Mistpiercer": 4,
   "Crossbow": 2,
   "Bow of Badon": 25,
   "Greataxe": 5,
   "Hellfire Hands": 5,
   "Whispering Bow": 4,
   "Holy Staff": 18,
   "Blazing Staff": 2,
   "Bear Paws": 15,
   "Twin Slayers": 3,
   "Staff of Balance": 1,
   "Glacial Staff": 1,
   "Warbow": 5,
   "Brawler Gloves": 6,
   "Crystal Reaper": 2,
   "Deathgivers": 4,
   "Pike": 1,
   "Demonic Staff": 1,
   "Longbow": 12,
   "Battleaxe": 8,
   "Dagger Pair": 9,
   "Forcepulse Bracers": 1,
   "Broadsword": 4,
   "Tombhammer": 1,
   "Blight Staff": 2,
   "Heron Spear": 3,
   "Infernal Scythe": 3,
   "Grailseeker": 1,
   "Hellspawn Staff": 1,
   "Hallowfall": 2,
   "Kingmaker": 1,
   "Great Holy Staff": 1,
   "Arclight Blasters": 3,
   "Soulscythe": 1,
   "Energy Shaper": 4,
   "Prowling Staff": 1,
   "Spirithunter": 1,
   "Claymore": 2,
   "Heavy Crossbow": 3,
   "Fists of Avalon": 2,
   "Bloodletter": 2,
   "Carrioncaller": 1,
   "Redemption Staff": 2,
   "Realmbreaker": 2,
   "Ursine Maulers": 2,
   "Great Fire Staff": 1,
   "Cursed Staff": 2,
   "Black Monk Stave": 1,
   "Carving Sword": 1
  },
  "Broadsword": {
   "Cursed Staff": 2,
   "Fists of Avalon": 2,
   "Holy Staff": 6,
   "Battleaxe": 2,
   "Greataxe": 1,
   "Blight Staff": 1,
   "Bow of Badon": 1,
   "Kingmaker": 1,
   "Ironroot Staff": 1,
   "Deathgivers": 2,
   "Claymore": 1,
   "Bear Paws": 1,
   "Divine Staff": 1,
   "Great Holy Staff": 2,
   "Heron Spear": 1,
   "Soulscythe": 1,
   "Dagger Pair": 2,
   "Hellfire Hands": 3
  },
  "Bear Paws": {
   "Bow of Badon": 8,
   "Holy Staff": 17,
   "Broadsword": 2,
   "Claymore": 3,
   "Dagger Pair": 3,
   "Bloodletter": 8,
   "Hallowfall": 1,
   "Hellspawn Staff": 4,
   "Deathgivers": 1,
   "Mistpiercer": 2,
   "Heavy Crossbow": 1,
   "Crossbow": 3,
   "Hellfire Hands": 1,
   "Great Fire Staff": 1,
   "Longbow": 7,
   "Fists of Avalon": 1,
   "Ironroot Staff": 1,
   "Battleaxe": 16,
   "Bear Paws": 5,
   "Heron Spear": 1,
   "Permafrost Prism": 1,
   "Bedrock Mace": 2,
   "Pike": 2,
   "Greataxe": 8,
   "Whispering Bow": 1,
   "Grailseeker": 1,
   "Infernal Scythe": 2,
   "Blazing Staff": 1,
   "Dagger": 1,
   "Cursed Staff": 3,
   "Arclight Blasters": 2,
   "Demonic Staff": 1,
   "Lifecurse Staff": 1,
   "Blight Staff": 2,
   "Carving Sword": 3,
   "Warbow": 3,
   "Brawler Gloves": 1,
   "Dawnsong": 1,
   "Energy Shaper": 1
  },
  "Mistpiercer": {
   "Arclight Blasters": 2,
   "Fists of Avalon": 1,
   "Bedrock Mace": 1,
   "Longbow": 2,
   "Infernal Scythe": 2,
   "Bow of Badon": 1,
   "Battleaxe": 2,
   "Grailseeker": 1,
   "Holy Staff": 3,
   "Bloodletter": 1,
   "Dagger Pair": 2,
   "Realmbreaker": 1,
   "Carving Sword": 1,
   "Hellfire Hands": 1
  },
  "Holy Staff": {
   "Dagger": 12,
   "Battleaxe": 46,
   "Longbow": 32,
   "Mistpiercer": 13,
   "Claymore": 96,
   "Holy Staff": 441,
   "Heavy Crossbow": 104,
   "Bow of Badon": 62,
   "Bear Paws": 25,
   "Greataxe": 17,
   "Dagger Pair": 81,
   "Cursed Staff": 27,
   "Carrioncaller": 23,
   "Blazing Staff": 13,
   "Arclight Blasters": 21,
   "Carving Sword": 18,
   "Fists of Avalon": 13,
   "Demonic Staff": 43,
   "Hallowfall": 13,
   "Deathgivers": 21,
   "Warbow": 28,
   "Staff of Balance": 24,
   "Whispering Bow": 12,
   "Hellspawn Staff": 39,
   "Hellfire Hands": 19,
   "Energy Shaper": 6,
   "Brawler Gloves": 48,
   "Rotcaller Staff": 2,
   "Bloodletter": 17,
   "Crossbow": 16,
   "Wildfire Staff": 8,
   "Divine Staff": 5,
   "Tombhammer": 20,
   "Great Fire Staff": 10,
   "Blight Staff": 10,
   "Permafrost Prism": 2,
   "Lifecurse Staff": 5,
   "Spirithunter": 5,
   "Soulscythe": 11,
   "Ironroot Staff": 10,
   "Broadsword": 8,
   "Glacial Staff": 9,
   "Daybreaker": 1,
   "Great Holy Staff": 16,
   "Ursine Maulers": 2,
   "Forcepulse Bracers": 2,
   "Realmbreaker": 5,
   "Kingmaker": 10,
   "Twin Slayers": 8,
   "Crystal Reaper": 8,
   "Redemption Staff": 12,
   "Heron Spear": 12,
   "Grailseeker": 16,
   "Dawnsong": 1,
   "Infernal Scythe": 3,
   "Prowling Staff": 12,
   "Pike": 3,
   "Glaive": 2,
   "Black Monk Stave": 1,
   "Icicle Staff": 1,
   "Occult Staff": 1
  },
  "Divine Staff": {
   "Grailseeker": 1,
   "Holy Staff": 3,
   "Heavy Crossbow": 1,
   "Bear Paws": 3,
   "Hallowfall": 1,
   "Dagger Pair": 1,
   "Blight Staff": 2,
   "Cursed Staff": 1
  },
  "Dagger": {
   "Holy Staff": 24,
   "Heron Spear": 3,
   "Dagger Pair": 6,
   "Heavy Crossbow": 5,
   "Brawler Gloves": 5,
   "Bow of Badon": 2,
   "Claymore": 5,
   "Fists of Avalon": 1,
   "Hallowfall": 1,
   "Staff of Balance": 1,
   "Cursed Staff": 1,
   "Prowling Staff": 1,
   "Battleaxe": 5,
   "Warbow": 2,
   "Kingmaker": 2,
   "Greataxe": 2,
   "Arclight Blasters": 2,
   "Crossbow": 1,
   "Dagger": 1,
   "Wildfire Staff": 1,
   "Tombhammer": 1,
   "Lifecurse Staff": 1,
   "Demonic Staff": 1,
   "Grailseeker": 1
  },
  "Grailseeker": {
   "Claymore": 6,
   "Blight Staff": 1,
   "Lifecurse Staff": 2,
   "Dagger Pair": 6,
   "Holy Staff": 18,
   "Heavy Crossbow": 5,
   "Brawler Gloves": 5,
   "Mistpiercer": 1,
   "Crystal Reaper": 2,
   "Bow of Badon": 5,
   "Greataxe": 6,
   "Cursed Staff": 1,
   "Warbow": 5,
   "Battleaxe": 6,
   "Infernal Scythe": 1,
   "Blazing Staff": 2,
   "Heron Spear": 4,
   "Great Holy Staff": 2,
   "Arclight Blasters": 1,
   "Longbow": 3,
   "Great Fire Staff": 1,
   "Dagger": 1,
   "Crossbow": 2,
   "Hallowfall": 1,
   "Deathgivers": 1,
   "Whispering Bow": 1,
   "Black Monk Stave": 1,
   "Demonic Staff": 1,
   "Grailseeker": 1,
   "Great Arcane Staff": 1,
   "Kingmaker": 1
  },
  "Cursed Staff": {
   "Battleaxe": 8,
   "Warbow": 4,
   "Cursed Staff": 1,
   "Longbow": 4,
   "Holy Staff": 10,
   "Lifecurse Staff": 2,
   "Dagger Pair": 6,
   "Brawler Gloves": 2,
   "Hellspawn Staff": 1,
   "Deathgivers": 3,
   "Whispering Bow": 1,
   "Claymore": 3,
   "Wildfire Staff": 2,
   "Hellfire Hands": 2,
   "Dawnsong": 1,
   "Fists of Avalon": 1,
   "Heavy Crossbow": 4,
   "Bow of Badon": 6,
   "Bedrock Mace": 1,
   "Kingmaker": 2,
   "Bloodletter": 2,
   "Great Fire Staff": 1,
   "Spirithunter": 1,
   "Carrioncaller": 1,
   "Blazing Staff": 1,
   "Grailseeker": 1,
   "Broadsword": 1,
   "Hallowfall": 1,
   "Bear Paws": 1,
   "Crystal Reaper": 1,
   "Mistpiercer": 1,
   "Greataxe": 2,
   "Dagger": 1,
   "Heron Spear": 1,
   "Arclight Blasters": 1,
   "Demonic Staff": 1
  },
  "Brawler Gloves": {
   "Battleaxe": 5,
   "Holy Staff": 42,
   "Bloodletter": 4,
   "Crossbow": 2,
   "Claymore": 10,
   "Heavy Crossbow": 1,
   "Mistpiercer": 1,
   "Prowling Staff": 1,
   "Carving Sword": 2,
   "Hellspawn Staff": 2,
   "Demonic Staff": 8,
   "Longbow": 2,
   "Cursed Staff": 3,
   "Hallowfall": 1,
   "Grailseeker": 1,
   "Bow of Badon": 4,
   "Deathgivers": 2,
   "Blight Staff": 1,
   "Black Monk Stave": 2,
   "Dagger": 2,
   "Fists of Avalon": 2,
   "Great Holy Staff": 4,
   "Staff of Balance": 1,
   "Infernal Scythe": 1,
   "Divine Staff": 1,
   "Carrioncaller": 1,
   "Dagger Pair": 7,
   "Warbow": 2,
   "Glacial Staff": 2,
   "Brawler Gloves": 1,
   "Tombhammer": 1,
   "Crystal Reaper": 1,
   "Greataxe": 2
  },
  "Carving Sword": {
   "Heron Spear": 1,
   "Bow of Badon": 6,
   "Holy Staff": 24,
   "Arclight Blasters": 3,
   "Carving Sword": 2,
   "Fists of Avalon": 1,
   "Whispering Bow": 1,
   "Blight Staff": 2,
   "Claymore": 3,
   "Tombhammer": 1,
   "Battleaxe": 6,
   "Ursine Maulers": 1,
   "Twin Slayers": 1,
   "Bloodletter": 4,
   "Crossbow": 4,
   "Carrioncaller": 1,
   "Dawnsong": 2,
   "Warbow": 1,
   "Heavy Crossbow": 4,
   "Prowling Staff": 2,
   "Staff of Balance": 2,
   "Blazing Staff": 2,
   "Crystal Reaper": 2,
   "Hellspawn Staff": 1,
   "Deathgivers": 1,
   "Bear Paws": 3,
   "Mistpiercer": 1,
   "Greataxe": 2,
   "Grailseeker": 1,
   "Demonic Staff": 3,
   "Cursed Staff": 3,
   "Dagger Pair": 3,
   "Energy Shaper": 1,
   "Longbow": 2,
   "Lifecurse Staff": 2
  },
  "Fists of Avalon": {
   "Heron Spear": 1,
   "Holy Staff": 18,
   "Bow of Badon": 4,
   "Whispering Bow": 2,
   "Warbow": 2,
   "Longbow": 3,
   "Twin Slayers": 1,
   "Hallowfall": 1,
   "Arclight Blasters": 1,
   "Hellfire Hands": 3,
   "Claymore": 3,
   "Demonic Staff": 1,
   "Kingmaker": 1,
   "Heavy Crossbow": 3,
   "Infernal Scythe": 2,
   "Dagger Pair": 2,
   "Blight Staff": 3,
   "Battleaxe": 4,
   "Bear Paws": 3,
   "Prowling Staff": 1,
   "Carving Sword": 2,
   "Bloodletter": 3,
   "Grailseeker": 1,
   "Broadsword": 1,
   "Wildfire Staff": 1,
   "Staff of Balance": 1,
   "Dagger": 1,
   "Hellspawn Staff": 1,
   "Cursed Staff": 2,
   "Brawler Gloves": 2,
   "Crystal Reaper": 1,
   "Crossbow": 1
  },
  "Energy Shaper": {
   "Bear Paws": 2,
   "Warbow": 1,
   "Heron Spear": 1,
   "Mistpiercer": 1,
   "Energy Shaper": 1,
   "Bow of Badon": 3,
   "Holy Staff": 3,
   "Longbow": 1,
   "Deathgivers": 1,
   "Whispering Bow": 1,
   "Kingmaker": 1,
   "Brawler Gloves": 1,
   "Arclight Blasters": 1
  },
  "Tombhammer": {
   "Bear Paws": 5,
   "Bloodletter": 1,
   "Bow of Badon": 4,
   "Holy Staff": 16,
   "Bedrock Mace": 1,
   "Hellfire Hands": 3,
   "Great Holy Staff": 1,
   "Fists of Avalon": 2,
   "Warbow": 3,
   "Black Monk Stave": 2,
   "Deathgivers": 1,
   "Prowling Staff": 1,
   "Grailseeker": 1,
   "Dagger": 1,
   "Arclight Blasters": 3,
   "Hallowfall": 1,
   "Broadsword": 1,
   "Dagger Pair": 2,
   "Twin Slayers": 1,
   "Heron Spear": 3,
   "Blazing Staff": 1,
   "Whispering Bow": 1,
   "Longbow": 1,
   "Demonic Staff": 1,
   "Carrioncaller": 1,
   "Infernal Scythe": 2,
   "Realmbreaker": 1,
   "Crossbow": 1,
   "Brawler Gloves": 3,
   "Claymore": 2,
   "Carving Sword": 1,
   "Heavy Crossbow": 1,
   "Tombhammer": 2,
   "Staff of Balance": 1
  },
  "Hallowfall": {
   "Lifecurse Staff": 2,
   "Hallowfall": 1,
   "Hellfire Hands": 1,
   "Bow of Badon": 6,
   "Spirithunter": 1,
   "Blazing Staff": 2,
   "Tombhammer": 1,
   "Battleaxe": 3,
   "Ursine Maulers": 1,
   "Bedrock Mace": 1,
   "Holy Staff": 5,
   "Hellspawn Staff": 1,
   "Energy Shaper": 1,
   "Dawnsong": 1,
   "Warbow": 1,
   "Glacial Staff": 1,
   "Dagger Pair": 1,
   "Crossbow": 2,
   "Crystal Reaper": 1,
   "Longbow": 2,
   "Cursed Staff": 1,
   "Bear Paws": 2,
   "Twin Slayers": 1,
   "Heron Spear": 1,
   "Infernal Scythe": 1,
   "Black Monk Stave": 1
  },
  "Wildfire Staff": {
   "Cursed Staff": 1,
   "Battleaxe": 2,
   "Claymore": 2,
   "Heavy Crossbow": 4,
   "Dagger Pair": 1,
   "Longbow": 1,
   "Holy Staff": 2,
   "Warbow": 1,
   "Deathgivers": 1,
   "Blazing Staff": 1,
   "Bloodletter": 1,
   "Mistpiercer": 1
  },
  "Blight Staff": {
   "Cursed Staff": 2,
   "Longbow": 2,
   "Twin Slayers": 1,
   "Blazing Staff": 1,
   "Battleaxe": 1,
   "Dagger": 1,
   "Bow of Badon": 3,
   "Broadsword": 1,
   "Wildfire Staff": 1,
   "Lifecurse Staff": 1,
   "Brawler Gloves": 1
  },
  "Infernal Scythe": {
   "Hellfire Hands": 1,
   "Whispering Bow": 1,
   "Staff of Balance": 1,
   "Glacial Staff": 1,
   "Bow of Badon": 3,
   "Holy Staff": 4,
   "Crossbow": 1,
   "Cursed Staff": 1,
   "Battleaxe": 1,
   "Great Holy Staff": 1
  },
  "Crossbow": {
   "Dagger Pair": 3,
   "Dagger": 1,
   "Infernal Scythe": 1,
   "Great Holy Staff": 1,
   "Battleaxe": 5,
   "Hallowfall": 2,
   "Carrioncaller": 1,
   "Great Fire Staff": 1,
   "Blight Staff": 1,
   "Brawler Gloves": 2,
   "Bear Paws": 3,
   "Cursed Staff": 1,
   "Glaive": 1,
   "Deathgivers": 1,
   "Bow of Badon": 6,
   "Bedrock Mace": 1,
   "Greataxe": 2,
   "Redemption Staff": 1,
   "Claymore": 3,
   "Holy Staff": 9,
   "Wildfire Staff": 1,
   "Carving Sword": 2,
   "Warbow": 1,
   "Hellfire Hands": 1
  },
  "Longbow": {
   "Pike": 2,
   "Holy Staff": 7,
   "Battleaxe": 14,
   "Cursed Staff": 4,
   "Great Fire Staff": 2,
   "Bloodletter": 2,
   "Heavy Crossbow": 2,
   "Crossbow": 3,
   "Dawnsong": 2,
   "Warbow": 2,
   "Bear Paws": 5,
   "Forcepulse Bracers": 1,
   "Longbow": 8,
   "Lifecurse Staff": 2,
   "Dagger Pair": 4,
   "Whispering Bow": 3,
   "Bow of Badon": 8,
   "Energy Shaper": 3,
   "Greataxe": 4,
   "Infernal Scythe": 3,
   "Redemption Staff": 1,
   "Staff of Balance": 2,
   "Carving Sword": 1,
   "Grailseeker": 2,
   "Realmbreaker": 1,
   "Great Holy Staff": 1,
   "Crystal Reaper": 2,
   "Blazing Staff": 4,
   "Mistpiercer": 1,
   "Arclight Blasters": 2,
   "Fists of Avalon": 2,
   "Twin Slayers": 2,
   "Claymore": 1,
   "Hellfire Hands": 1
  },
  "Great Holy Staff": {
   "Greataxe": 3,
   "Battleaxe": 2,
   "Hellfire Hands": 2,
   "Bloodletter": 2,
   "Crossbow": 2,
   "Holy Staff": 10,
   "Longbow": 2,
   "Dagger": 1,
   "Grailseeker": 1,
   "Great Fire Staff": 1,
   "Bear Paws": 1,
   "Bow of Badon": 2,
   "Brawler Gloves": 1,
   "Arclight Blasters": 3,
   "Carving Sword": 1,
   "Carrioncaller": 1,
   "Claymore": 2,
   "Demonic Staff": 1
  },
  "Pike": {
   "Bloodletter": 1,
   "Greataxe": 1,
   "Holy Staff": 4,
   "Heavy Crossbow": 1,
   "Whispering Bow": 1,
   "Deathgivers": 2,
   "Cursed Staff": 1,
   "Prowling Staff": 1,
   "Hellspawn Staff": 1,
   "Bear Paws": 2,
   "Claymore": 1,
   "Blight Staff": 1
  },
  "Heron Spear": {
   "Lifecurse Staff": 1,
   "Twin Slayers": 1,
   "Warbow": 5,
   "Dagger Pair": 8,
   "Bear Paws": 2,
   "Longbow": 3,
   "Holy Staff": 12,
   "Staff of Balance": 1,
   "Glacial Staff": 1,
   "Grailseeker": 1,
   "Energy Shaper": 2,
   "Hellspawn Staff": 1,
   "Bow of Badon": 2,
   "Great Fire Staff": 1,
   "Greataxe": 2,
   "Claymore": 6,
   "Black Monk Stave": 1,
   "Dawnsong": 1,
   "Hoarfrost Staff": 1,
   "Battleaxe": 3,
   "Fists of Avalon": 1,
   "Infernal Scythe": 1,
   "Crystal Reaper": 1,
   "Deathgivers": 2,
   "Demonic Staff": 2,
   "Blight Staff": 1,
   "Tombhammer": 3,
   "Bloodletter": 1,
   "Great Holy Staff": 2,
   "Cursed Staff": 2,
   "Arclight Blasters": 1,
   "Brawler Gloves": 1
  },
  "Kingmaker": {
   "Warbow": 2,
   "Bow of Badon": 2,
   "Holy Staff": 7,
   "Claymore": 3,
   "Deathgivers": 1,
   "Blazing Staff": 2,
   "Battleaxe": 2,
   "Bear Paws": 2,
   "Great Fire Staff": 2,
   "Heavy Crossbow": 1,
   "Grailseeker": 1,
   "Dagger": 1,
   "Tombhammer": 2,
   "Cursed Staff": 1,
   "Dagger Pair": 2,
   "Hellspawn Staff": 1,
   "Rotcaller Staff": 1,
   "Mistpiercer": 1,
   "Redemption Staff": 1,
   "Longbow": 1,
   "Fists of Avalon": 1
  },
  "Bloodletter": {
   "Infernal Scythe": 1,
   "Great Holy Staff": 1,
   "Cursed Staff": 3,
   "Lifecurse Staff": 1,
   "Hallowfall": 2,
   "Carrioncaller": 1,
   "Great Fire Staff": 1,
   "Blight Staff": 2,
   "Holy Staff": 12,
   "Prowling Staff": 1,
   "Brawler Gloves": 3,
   "Wildfire Staff": 1,
   "Bloodletter": 3,
   "Battleaxe": 9,
   "Great Arcane Staff": 1,
   "Glaive": 1,
   "Heavy Crossbow": 1,
   "Bow of Badon": 2,
   "Claymore": 8,
   "Heron Spear": 1,
   "Arclight Blasters": 1,
   "Longbow": 3,
   "Whispering Bow": 1,
   "Deathgivers": 2,
   "Bear Paws": 2,
   "Grailseeker": 1,
   "Dagger Pair": 3,
   "Carving Sword": 1,
   "Warbow": 7,
   "Mistpiercer": 1,
   "Ursine Maulers": 1,
   "Demonic Staff": 2,
   "Hellspawn Staff": 1,
   "Kingmaker": 1,
   "Blazing Staff": 1
  },
  "Prowling Staff": {
   "Bow of Badon": 4,
   "Wildfire Staff": 1,
   "Holy Staff": 17,
   "Hellspawn Staff": 1,
   "Brawler Gloves": 2,
   "Blazing Staff": 3,
   "Tombhammer": 1,
   "Arclight Blasters": 4,
   "Kingmaker": 2,
   "Black Monk Stave": 1,
   "Dagger": 1,
   "Warbow": 1,
   "Heavy Crossbow": 6,
   "Fists of Avalon": 1,
   "Staff of Balance": 1,
   "Carrioncaller": 1,
   "Dagger Pair": 1,
   "Glaive": 1,
   "Claymore": 3,
   "Demonic Staff": 1,
   "Carving Sword": 1,
   "Longbow": 1,
   "Broadsword": 1
  },
  "Redemption Staff": {
   "Deathgivers": 1,
   "Bow of Badon": 1,
   "Forcepulse Bracers": 1,
   "Carrioncaller": 1,
   "Holy Staff": 2,
   "Heavy Crossbow": 1,
   "Claymore": 1,
   "Battleaxe": 1,
   "Longbow": 2,
   "Crossbow": 3,
   "Hellspawn Staff": 1,
   "Grailseeker": 1,
   "Energy Shaper": 1,
   "Dagger": 1,
   "Heron Spear": 1,
   "Carving Sword": 1
  },
  "Crystal Reaper": {
   "Bloodletter": 1,
   "Mistpiercer": 2,
   "Battleaxe": 4,
   "Holy Staff": 5,
   "Warbow": 2,
   "Crystal Reaper": 1,
   "Hallowfall": 2,
   "Twin Slayers": 1,
   "Hellspawn Staff": 1,
   "Bow of Badon": 4,
   "Greataxe": 2,
   "Longbow": 6,
   "Bear Paws": 2,
   "Grailseeker": 1,
   "Energy Shaper": 1,
   "Crossbow": 1,
   "Heron Spear": 1,
   "Infernal Scythe": 1,
   "Blazing Staff": 1,
   "Dagger": 1,
   "Arclight Blasters": 1,
   "Claymore": 1
  },
  "Hellspawn Staff": {
   "Holy Staff": 43,
   "Cursed Staff": 6,
   "Claymore": 10,
   "Dagger Pair": 8,
   "Divine Staff": 1,
   "Heavy Crossbow": 7,
   "Carving Sword": 2,
   "Hellspawn Staff": 6,
   "Soulscythe": 3,
   "Spirithunter": 2,
   "Demonic Staff": 4,
   "Blazing Staff": 1,
   "Warbow": 1,
   "Great Holy Staff": 1,
   "Twin Slayers": 3,
   "Bow of Badon": 7,
   "Tombhammer": 3,
   "Bear Paws": 3,
   "Carrioncaller": 5,
   "Longbow": 4,
   "Energy Shaper": 2,
   "Arclight Blasters": 5,
   "Broadsword": 1,
   "Crystal Reaper": 2,
   "Mistpiercer": 3,
   "Grailseeker": 3,
   "Heron Spear": 3,
   "Dagger": 2,
   "Whispering Bow": 1,
   "Brawler Gloves": 3,
   "Staff of Balance": 1,
   "Kingmaker": 1,
   "Battleaxe": 2,
   "Hellfire Hands": 2,
   "Pike": 1,
   "Prowling Staff": 2,
   "Redemption Staff": 2,
   "Infernal Scythe": 1
  },
  "Soulscythe": {
   "Whispering Bow": 1,
   "Bear Paws": 1,
   "Claymore": 1,
   "Holy Staff": 4,
   "Battleaxe": 2,
   "Heavy Crossbow": 2,
   "Carrioncaller": 1,
   "Redemption Staff": 1,
   "Longbow": 1,
   "Glacial Staff": 1,
   "Bedrock Mace": 1,
   "Hellfire Hands": 1,
   "Bloodletter": 1,
   "Tombhammer": 1
  },
  "Rotcaller Staff": {
   "Hellspawn Staff": 1,
   "Holy Staff": 7,
   "Blight Staff": 1,
   "Great Holy Staff": 1,
   "Crystal Reaper": 1,
   "Demonic Staff": 1,
   "Kingmaker": 1,
   "Glaive": 1,
   "Carving Sword": 1,
   "Redemption Staff": 1
  },
  "Spirithunter": {
   "Bear Paws": 1,
   "Claymore": 1,
   "Holy Staff": 1,
   "Battleaxe": 1,
   "Grailseeker": 1,
   "Dagger": 1
  },
  "Blazing Staff": {
   "Mistpiercer": 1,
   "Brawler Gloves": 2,
   "Crystal Reaper": 1,
   "Bow of Badon": 3,
   "Greataxe": 3,
   "Cursed Staff": 2,
   "Battleaxe": 4,
   "Infernal Scythe": 1,
   "Blazing Staff": 1,
   "Heron Spear": 1,
   "Heavy Crossbow": 2,
   "Warbow": 1,
   "Holy Staff": 3,
   "Bloodletter": 1,
   "Tombhammer": 1,
   "Energy Shaper": 1,
   "Arclight Blasters": 1,
   "Great Arcane Staff": 1,
   "Kingmaker": 1
  },
  "Hellfire Hands": {
   "Blight Staff": 2,
   "Realmbreaker": 2,
   "Holy Staff": 21,
   "Forcepulse Bracers": 1,
   "Heavy Crossbow": 3,
   "Warbow": 2,
   "Fists of Avalon": 1,
   "Black Monk Stave": 1,
   "Deathgivers": 1,
   "Prowling Staff": 1,
   "Brawler Gloves": 2,
   "Dagger Pair": 4,
   "Mistpiercer": 1,
   "Arclight Blasters": 2,
   "Bow of Badon": 3,
   "Battleaxe": 1,
   "Crossbow": 2,
   "Hellspawn Staff": 2,
   "Claymore": 4,
   "Carving Sword": 2,
   "Hellfire Hands": 1,
   "Infernal Scythe": 1,
   "Grailseeker": 2,
   "Demonic Staff": 2,
   "Great Holy Staff": 1,
   "Tombhammer": 2,
   "Rotcaller Staff": 1,
   "Bloodletter": 1,
   "Blazing Staff": 1,
   "Crystal Reaper": 1,
   "Hallowfall": 2,
   "Permafrost Prism": 1
  },
  "Ironroot Staff": {
   "Dagger Pair": 3,
   "Holy Staff": 12,
   "Great Holy Staff": 1,
   "Prowling Staff": 1,
   "Heavy Crossbow": 2,
   "Claymore": 1,
   "Warbow": 3,
   "Brawler Gloves": 1,
   "Bow of Badon": 1,
   "Greataxe": 1,
   "Blight Staff": 2,
   "Deathgivers": 1,
   "Carving Sword": 2,
   "Battleaxe": 1,
   "Dagger": 1,
   "Heron Spear": 1,
   "Whispering Bow": 1,
   "Hellspawn Staff": 1
  },
  "Great Fire Staff": {
   "Battleaxe": 2,
   "Dagger Pair": 3,
   "Warbow": 1,
   "Bow of Badon": 1,
   "Dawnsong": 1,
   "Twin Slayers": 1,
   "Blazing Staff": 1,
   "Heron Spear": 1
  },
  "Realmbreaker": {
   "Bow of Badon": 5,
   "Ironroot Staff": 1,
   "Holy Staff": 1,
   "Claymore": 1,
   "Battleaxe": 2,
   "Blazing Staff": 1,
   "Lifecurse Staff": 1,
   "Dagger Pair": 1,
   "Redemption Staff": 1,
   "Cursed Staff": 1,
   "Crystal Reaper": 1
  },
  "Permafrost Prism": {
   "Hellfire Hands": 1,
   "Deathgivers": 1,
   "Bow of Badon": 1,
   "Longbow": 1
  },
  "Staff of Balance": {
   "Fists of Avalon": 1,
   "Holy Staff": 21,
   "Claymore": 4,
   "Bloodletter": 3,
   "Staff of Balance": 2,
   "Prowling Staff": 2,
   "Kingmaker": 1,
   "Battleaxe": 5,
   "Crossbow": 2,
   "Glacial Staff": 1,
   "Dagger Pair": 2,
   "Heavy Crossbow": 6,
   "Whispering Bow": 2,
   "Bear Paws": 1,
   "Soulscythe": 1,
   "Carving Sword": 1,
   "Greataxe": 1,
   "Tombhammer": 1,
   "Bow of Badon": 1,
   "Longbow": 2,
   "Wildfire Staff": 2,
   "Broadsword": 1,
   "Lifecurse Staff": 1,
   "Great Holy Staff": 1,
   "Crystal Reaper": 1,
   "Glaive": 1,
   "Hellfire Hands": 1,
   "Hoarfrost Staff": 1,
   "Cursed Staff": 1
  },
  "Glacial Staff": {
   "Bloodletter": 2,
   "Battleaxe": 4,
   "Crossbow": 2,
   "Whispering Bow": 2,
   "Bear Paws": 1,
   "Soulscythe": 1,
   "Holy Staff": 6,
   "Claymore": 1,
   "Longbow": 2,
   "Heavy Crossbow": 2,
   "Great Holy Staff": 1,
   "Crystal Reaper": 1,
   "Glaive": 1,
   "Staff of Balance": 1,
   "Hoarfrost Staff": 1,
   "Wildfire Staff": 1
  },
  "Twin Slayers": {
   "Hellspawn Staff": 2,
   "Holy Staff": 2,
   "Heavy Crossbow": 1,
   "Redemption Staff": 2,
   "Bear Paws": 2,
   "Bow of Badon": 2,
   "Forcepulse Bracers": 1,
   "Infernal Scythe": 1,
   "Battleaxe": 1,
   "Blight Staff": 1,
   "Arclight Blasters": 1
  },
  "Grovekeeper": {
   "Great Arcane Staff": 1,
   "Warbow": 1,
   "Bow of Badon": 1
  },
  "Hoarfrost Staff": {
   "Blazing Staff": 1,
   "Crossbow": 1
  },
  "Wailing Bow": {
   "Great Holy Staff": 2,
   "Dagger Pair": 1,
   "Hellfire Hands": 1
  },
  "Black Monk Stave": {
   "Battleaxe": 1,
   "Heron Spear": 1,
   "Kingmaker": 1
  },
  "Glaive": {
   "Brawler Gloves": 1,
   "Claymore": 5,
   "Heavy Crossbow": 2,
   "Holy Staff": 8,
   "Dagger Pair": 1,
   "Demonic Staff": 1,
   "Bloodletter": 1
  },
  "Daybreaker": {
   "Greataxe": 1,
   "Warbow": 1,
   "Battleaxe": 2,
   "Claymore": 1,
   "Crystal Reaper": 1,
   "Bear Paws": 1,
   "Holy Staff": 1,
   "Redemption Staff": 1,
   "Longbow": 1,
   "Bow of Badon": 1
  },
  "Lifecurse Staff": {
   "Holy Staff": 2,
   "Heavy Crossbow": 1,
   "Battleaxe": 1,
   "Staff of Balance": 1,
   "Dagger": 1,
   "Realmbreaker": 1
  },
  "Occult Staff": {
   "Occult Staff": 2
  },
  "Ursine Maulers": {
   "Arclight Blasters": 1,
   "Bow of Badon": 1,
   "Holy Staff": 1,
   "Longbow": 1
  },
  "Bedrock Mace": {
   "Broadsword": 1
  }
 },
 "duos": {
  "Energy Shaper + Tombhammer": {
   "Bear Paws + Bear Paws": 1,
   "Arclight Blasters + Holy Staff": 1
  },
  "Claymore + Holy Staff": {
   "Claymore + Holy Staff": 11,
   "Heavy Crossbow + Holy Staff": 17,
   "Dagger Pair + Holy Staff": 4,
   "Demonic Staff + Holy Staff": 11,
   "Hellfire Hands + Tombhammer": 2,
   "Bow of Badon + Lifecurse Staff": 1,
   "Bloodletter + Crossbow": 1,
   "Holy Staff + Wildfire Staff": 1,
   "Cursed Staff + Holy Staff": 3,
   "Crossbow + Crossbow": 1,
   "Brawler Gloves + Longbow": 2,
   "Brawler Gloves + Crossbow": 1,
   "Demonic Staff + Ironroot Staff": 1,
   "Carrioncaller + Holy Staff": 3,
   "Heavy Crossbow + Heavy Crossbow": 2,
   "Warbow + Warbow": 4,
   "Hellfire Hands + Holy Staff": 3,
   "Fists of Avalon + Holy Staff": 1,
   "Claymore + Ironroot Staff": 1,
   "Glacial Staff + Staff of Balance": 3,
   "Dagger Pair + Soulscythe": 1,
   "Brawler Gloves + Dagger Pair": 1,
   "Demonic Staff + Great Holy Staff": 1,
   "Battleaxe + Holy Staff": 2,
   "Dagger Pair + Dagger Pair": 2,
   "Hellspawn Staff + Holy Staff": 3,
   "Great Fire Staff + Holy Staff": 1,
   "Carving Sword + Holy Staff": 1,
   "Holy Staff + Prowling Staff": 2,
   "Dagger Pair + Ironroot Staff": 1,
   "Grailseeker + Great Fire Staff": 1,
   "Holy Staff + Realmbreaker": 1,
   "Carrioncaller + Longbow": 1,
   "Dagger Pair + Hellfire Hands": 1,
   "Carrioncaller + Hellfire Hands": 1,
   "Greataxe + Hellfire Hands": 1,
   "Arclight Blasters + Holy Staff": 2,
   "Dagger Pair + Great Holy Staff": 1,
   "Dagger Pair + Divine Staff": 1,
   "Brawler Gloves + Heavy Crossbow": 1,
   "Brawler Gloves + Heron Spear": 1,
   "Broadsword + Holy Staff": 1,
   "Whispering Bow + Whispering Bow": 1,
   "Glaive + Holy Staff": 1,
   "Battleaxe + Ironroot Staff": 1,
   "Dagger Pair + Warbow": 1,
   "Battleaxe + Forcepulse Bracers": 1,
   "Kingmaker + Wildfire Staff": 1,
   "Blazing Staff + Redemption Staff": 1
  },
  "Greataxe + Hallowfall": {
   "Hallowfall + Lifecurse Staff": 1
  },
  "Heavy Crossbow + Holy Staff": {
   "Bear Paws + Longbow": 1,
   "Heavy Crossbow + Holy Staff": 2,
   "Deathgivers + Holy Staff": 3,
   "Staff of Balance + Whispering Bow": 1,
   "Claymore + Holy Staff": 6,
   "Hellspawn Staff + Holy Staff": 3,
   "Hallowfall + Kingmaker": 1,
   "Carrioncaller + Holy Staff": 2,
   "Brawler Gloves + Warbow": 1,
   "Heavy Crossbow + Heavy Crossbow": 2,
   "Cursed Staff + Holy Staff": 1,
   "Dagger Pair + Holy Staff": 3,
   "Demonic Staff + Holy Staff": 2,
   "Bear Paws + Claymore": 1,
   "Battleaxe + Holy Staff": 1,
   "Greataxe + Hellfire Hands": 1,
   "Longbow + Warbow": 1,
   "Warbow + Warbow": 2,
   "Brawler Gloves + Heron Spear": 1,
   "Brawler Gloves + Heavy Crossbow": 1,
   "Hellfire Hands + Holy Staff": 1,
   "Bloodletter + Tombhammer": 1,
   "Holy Staff + Mistpiercer": 1
  },
  "Cursed Staff + Warbow": {
   "Cursed Staff + Longbow": 1
  },
  "Carving Sword + Holy Staff": {
   "Bow of Badon + Holy Staff": 1,
   "Carving Sword + Holy Staff": 1,
   "Arclight Blasters + Holy Staff": 1,
   "Blazing Staff + Staff of Balance": 1,
   "Heavy Crossbow + Holy Staff": 1,
   "Deathgivers + Holy Staff": 1,
   "Grailseeker + Mistpiercer": 1,
   "Battleaxe + Holy Staff": 2,
   "Demonic Staff + Holy Staff": 3,
   "Holy Staff + Prowling Staff": 1,
   "Holy Staff + Longbow": 1,
   "Bloodletter + Crossbow": 1,
   "Lifecurse Staff + Staff of Balance": 1
  },
  "Dagger Pair + Holy Staff": {
   "Carrioncaller + Holy Staff": 2,
   "Claymore + Holy Staff": 4,
   "Bear Paws + Holy Staff": 1,
   "Heavy Crossbow + Holy Staff": 2,
   "Holy Staff + Rotcaller Staff": 1,
   "Dagger Pair + Dagger Pair": 1,
   "Hellspawn Staff + Holy Staff": 2,
   "Blight Staff + Great Fire Staff": 2,
   "Dagger Pair + Holy Staff": 3,
   "Claymore + Ironroot Staff": 1,
   "Deathgivers + Holy Staff": 2,
   "Greataxe + Holy Staff": 1,
   "Battleaxe + Holy Staff": 1,
   "Demonic Staff + Holy Staff": 1,
   "Dagger Pair + Great Holy Staff": 1,
   "Crossbow + Holy Staff": 1,
   "Cursed Staff + Holy Staff": 1,
   "Tombhammer + Tombhammer": 1,
   "Glacial Staff + Staff of Balance": 1
  },
  "Bow of Badon + Holy Staff": {
   "Bear Paws + Blazing Staff": 1,
   "Brawler Gloves + Mistpiercer": 1,
   "Bow of Badon + Dagger Pair": 1,
   "Holy Staff + Holy Staff": 1,
   "Crystal Reaper + Twin Slayers": 1,
   "Grailseeker + Mistpiercer": 1,
   "Hellspawn Staff + Holy Staff": 1,
   "Deathgivers + Greataxe": 1,
   "Holy Staff + Longbow": 1,
   "Battleaxe + Heavy Crossbow": 1,
   "Dagger Pair + Dagger Pair": 1,
   "Blazing Staff + Redemption Staff": 1,
   "Hallowfall + Heavy Crossbow": 1,
   "Bear Paws + Brawler Gloves": 1,
   "Great Fire Staff + Holy Staff": 1,
   "Cursed Staff + Holy Staff": 1,
   "Bear Paws + Greataxe": 1,
   "Black Monk Stave + Longbow": 1
  },
  "Bow of Badon + Warbow": {
   "Hellfire Hands + Twin Slayers": 1
  },
  "Bear Paws + Holy Staff": {
   "Claymore + Holy Staff": 1,
   "Bow of Badon + Holy Staff": 1,
   "Hellspawn Staff + Ironroot Staff": 1,
   "Grailseeker + Mistpiercer": 1,
   "Battleaxe + Holy Staff": 1,
   "Bloodletter + Crossbow": 1
  },
  "Bow of Badon + Infernal Scythe": {
   "Glacial Staff + Staff of Balance": 1
  },
  "Dagger Pair + Divine Staff": {
   "Heavy Crossbow + Holy Staff": 1,
   "Bear Paws + Holy Staff": 1,
   "Bear Paws + Cursed Staff": 1
  },
  "Holy Staff + Kingmaker": {
   "Bow of Badon + Warbow": 1,
   "Claymore + Holy Staff": 1,
   "Deathgivers + Holy Staff": 1,
   "Dagger + Grailseeker": 1,
   "Claymore + Tombhammer": 1,
   "Battleaxe + Dagger Pair": 1,
   "Fists of Avalon + Warbow": 1
  },
  "Dagger + Grailseeker": {
   "Heavy Crossbow + Holy Staff": 2,
   "Bow of Badon + Brawler Gloves": 1,
   "Dagger Pair + Holy Staff": 1,
   "Claymore + Holy Staff": 4,
   "Brawler Gloves + Heron Spear": 1,
   "Demonic Staff + Holy Staff": 1,
   "Dagger Pair + Grailseeker": 1
  },
  "Arclight Blasters + Holy Staff": {
   "Bow of Badon + Bow of Badon": 1,
   "Carrioncaller + Holy Staff": 2,
   "Claymore + Holy Staff": 3,
   "Claymore + Great Holy Staff": 3,
   "Longbow + Realmbreaker": 1,
   "Battleaxe + Bow of Badon": 2,
   "Arclight Blasters + Ironroot Staff": 1,
   "Demonic Staff + Holy Staff": 1,
   "Claymore + Ironroot Staff": 1,
   "Bow of Badon + Greataxe": 1,
   "Deathgivers + Holy Staff": 2,
   "Heavy Crossbow + Warbow": 1,
   "Holy Staff + Wildfire Staff": 1,
   "Bear Paws + Holy Staff": 1,
   "Battleaxe + Holy Staff": 1,
   "Heavy Crossbow + Holy Staff": 1,
   "Holy Staff + Longbow": 1,
   "Glacial Staff + Ironroot Staff": 1,
   "Brawler Gloves + Heron Spear": 2,
   "Holy Staff + Kingmaker": 1,
   "Bear Paws + Warbow": 1,
   "Hellspawn Staff + Holy Staff": 1,
   "Dagger Pair + Holy Staff": 1,
   "Arclight Blasters + Great Holy Staff": 1
  },
  "Hellspawn Staff + Holy Staff": {
   "Cursed Staff + Holy Staff": 3,
   "Claymore + Holy Staff": 8,
   "Dagger Pair + Divine Staff": 1,
   "Heavy Crossbow + Holy Staff": 1,
   "Hellspawn Staff + Holy Staff": 3,
   "Demonic Staff + Holy Staff": 4,
   "Dagger Pair + Holy Staff": 3,
   "Dagger Pair + Soulscythe": 1,
   "Great Holy Staff + Hellspawn Staff": 1,
   "Arclight Blasters + Holy Staff": 1,
   "Broadsword + Holy Staff": 1,
   "Soulscythe + Twin Slayers": 1,
   "Arclight Blasters + Crystal Reaper": 1,
   "Grailseeker + Mistpiercer": 1,
   "Bear Paws + Bow of Badon": 1,
   "Dagger + Grailseeker": 1,
   "Carrioncaller + Heavy Crossbow": 1,
   "Bear Paws + Claymore": 1,
   "Carrioncaller + Holy Staff": 3,
   "Dagger + Staff of Balance": 1,
   "Brawler Gloves + Heron Spear": 1,
   "Holy Staff + Prowling Staff": 1,
   "Bow of Badon + Holy Staff": 1,
   "Bow of Badon + Redemption Staff": 1
  },
  "Holy Staff + Rotcaller Staff": {
   "Hellspawn Staff + Holy Staff": 1,
   "Crystal Reaper + Holy Staff": 1,
   "Demonic Staff + Holy Staff": 1,
   "Holy Staff + Kingmaker": 1,
   "Glaive + Holy Staff": 1
  },
  "Battleaxe + Holy Staff": {
   "Bloodletter + Crossbow": 1,
   "Bow of Badon + Permafrost Prism": 1,
   "Longbow + Longbow": 1,
   "Dagger Pair + Mistpiercer": 1,
   "Carving Sword + Holy Staff": 2,
   "Claymore + Holy Staff": 2,
   "Bow of Badon + Holy Staff": 1,
   "Deathgivers + Hellspawn Staff": 1,
   "Battleaxe + Holy Staff": 1,
   "Fists of Avalon + Soulscythe": 1,
   "Dagger Pair + Holy Staff": 1,
   "Heavy Crossbow + Wildfire Staff": 1,
   "Cursed Staff + Holy Staff": 2,
   "Heavy Crossbow + Tombhammer": 1,
   "Holy Staff + Prowling Staff": 1,
   "Deathgivers + Icicle Staff": 1,
   "Deathgivers + Holy Staff": 1,
   "Cursed Staff + Longbow": 1
  },
  "Cursed Staff + Holy Staff": {
   "Dagger Pair + Holy Staff": 1,
   "Hellspawn Staff + Holy Staff": 1,
   "Lifecurse Staff + Whispering Bow": 1,
   "Fists of Avalon + Heavy Crossbow": 1,
   "Heavy Crossbow + Warbow": 1,
   "Heavy Crossbow + Holy Staff": 1,
   "Grailseeker + Kingmaker": 1,
   "Bow of Badon + Claymore": 1
  },
  "Bloodletter + Crossbow": {
   "Carrioncaller + Hallowfall": 1,
   "Blight Staff + Great Fire Staff": 1,
   "Battleaxe + Holy Staff": 1,
   "Claymore + Holy Staff": 1
  },
  "Greataxe + Holy Staff": {
   "Blight Staff + Great Fire Staff": 1,
   "Soulscythe + Spirithunter": 1,
   "Hellspawn Staff + Holy Staff": 1,
   "Battleaxe + Bloodletter": 1,
   "Longbow + Redemption Staff": 1
  },
  "Soulscythe + Spirithunter": {
   "Bear Paws + Claymore": 1,
   "Battleaxe + Holy Staff": 1
  },
  "Blazing Staff + Grailseeker": {
   "Brawler Gloves + Mistpiercer": 1,
   "Bow of Badon + Crystal Reaper": 1
  },
  "Demonic Staff + Holy Staff": {
   "Dagger Pair + Dagger Pair": 1,
   "Claymore + Holy Staff": 11,
   "Heavy Crossbow + Holy Staff": 3,
   "Battleaxe + Holy Staff": 1,
   "Brawler Gloves + Holy Staff": 1,
   "Holy Staff + Longbow": 1,
   "Broadsword + Holy Staff": 1,
   "Brawler Gloves + Brawler Gloves": 1,
   "Dagger Pair + Holy Staff": 4,
   "Deathgivers + Holy Staff": 2,
   "Staff of Balance + Wildfire Staff": 1,
   "Carving Sword + Holy Staff": 1,
   "Arclight Blasters + Holy Staff": 2,
   "Demonic Staff + Holy Staff": 3,
   "Fists of Avalon + Staff of Balance": 1,
   "Pike + Pike": 1,
   "Dagger + Grailseeker": 3,
   "Holy Staff + Prowling Staff": 1,
   "Glacial Staff + Staff of Balance": 2,
   "Claymore + Claymore": 1,
   "Dagger Pair + Heavy Crossbow": 1,
   "Hellspawn Staff + Holy Staff": 1
  },
  "Brawler Gloves + Dagger Pair": {
   "Bloodletter + Crossbow": 1,
   "Claymore + Holy Staff": 1,
   "Demonic Staff + Holy Staff": 1
  },
  "Deathgivers + Holy Staff": {
   "Claymore + Holy Staff": 1,
   "Carrioncaller + Holy Staff": 1,
   "Brawler Gloves + Whispering Bow": 1,
   "Blazing Staff + Staff of Balance": 1,
   "Carving Sword + Holy Staff": 1,
   "Brawler Gloves + Longbow": 1,
   "Holy Staff + Lifecurse Staff": 1,
   "Heavy Crossbow + Heron Spear": 1,
   "Battleaxe + Bow of Badon": 1
  },
  "Claymore + Ironroot Staff": {
   "Dagger Pair + Holy Staff": 2,
   "Brawler Gloves + Warbow": 1,
   "Deathgivers + Holy Staff": 1,
   "Carving Sword + Holy Staff": 1,
   "Warbow + Warbow": 1,
   "Hellspawn Staff + Holy Staff": 1
  },
  "Brawler Gloves + Whispering Bow": {
   "Claymore + Holy Staff": 1,
   "Bloodletter + Crossbow": 1
  },
  "Carrioncaller + Holy Staff": {
   "Bloodletter + Crossbow": 2,
   "Bear Paws + Holy Staff": 1,
   "Carrioncaller + Holy Staff": 2,
   "Demonic Staff + Holy Staff": 3,
   "Hellspawn Staff + Holy Staff": 3,
   "Claymore + Great Holy Staff": 1,
   "Dagger Pair + Holy Staff": 2,
   "Heavy Crossbow + Holy Staff": 1,
   "Carving Sword + Holy Staff": 1,
   "Dagger Pair + Dagger Pair": 2,
   "Fists of Avalon + Soulscythe": 1,
   "Arclight Blasters + Great Holy Staff": 2,
   "Claymore + Holy Staff": 1,
   "Holy Staff + Prowling Staff": 2
  },
  "Realmbreaker + Tombhammer": {
   "Bow of Badon + Bow of Badon": 1
  },
  "Bloodletter + Brawler Gloves": {
   "Holy Staff + Prowling Staff": 1,
   "Demonic Staff + Holy Staff": 1
  },
  "Holy Staff + Prowling Staff": {
   "Brawler Gloves + Brawler Gloves": 1,
   "Bow of Badon + Holy Staff": 2,
   "Holy Staff + Kingmaker": 2,
   "Heavy Crossbow + Holy Staff": 1,
   "Fists of Avalon + Staff of Balance": 1,
   "Demonic Staff + Holy Staff": 1,
   "Carving Sword + Longbow": 1,
   "Claymore + Holy Staff": 2,
   "Arclight Blasters + Holy Staff": 2
  },
  "Brawler Gloves + Brawler Gloves": {
   "Carving Sword + Holy Staff": 1,
   "Black Monk Stave + Dagger": 1,
   "Fists of Avalon + Holy Staff": 1,
   "Claymore + Great Holy Staff": 1,
   "Claymore + Holy Staff": 1,
   "Bow of Badon + Greataxe": 1
  },
  "Crystal Reaper + Holy Staff": {
   "Mistpiercer + Mistpiercer": 1,
   "Battleaxe + Holy Staff": 1,
   "Warbow + Warbow": 1,
   "Holy Staff + Twin Slayers": 1,
   "Bow of Badon + Greataxe": 1
  },
  "Demonic Staff + Ironroot Staff": {
   "Great Holy Staff + Prowling Staff": 1
  },
  "Bow of Badon + Brawler Gloves": {
   "Demonic Staff + Longbow": 1
  },
  "Brawler Gloves + Warbow": {
   "Cursed Staff + Holy Staff": 1
  },
  "Dagger + Staff of Balance": {
   "Fists of Avalon + Holy Staff": 1,
   "Dagger Pair + Heavy Crossbow": 1,
   "Dagger Pair + Holy Staff": 1
  },
  "Carving Sword + Hallowfall": {
   "Battleaxe + Ursine Maulers": 1
  },
  "Warbow + Warbow": {
   "Bow of Badon + Mistpiercer": 1,
   "Holy Staff + Kingmaker": 1
  },
  "Dagger Pair + Ironroot Staff": {
   "Claymore + Holy Staff": 1
  },
  "Brawler Gloves + Dagger": {
   "Cursed Staff + Hallowfall": 1
  },
  "Holy Staff + Wildfire Staff": {
   "Heavy Crossbow + Heavy Crossbow": 1
  },
  "Heavy Crossbow + Heavy Crossbow": {
   "Deathgivers + Holy Staff": 1,
   "Bear Paws + Claymore": 1
  },
  "Hellfire Hands + Holy Staff": {
   "Heavy Crossbow + Holy Staff": 1,
   "Warbow + Warbow": 1,
   "Brawler Gloves + Dagger Pair": 1,
   "Hellspawn Staff + Holy Staff": 2,
   "Claymore + Holy Staff": 3,
   "Carving Sword + Holy Staff": 2,
   "Demonic Staff + Great Holy Staff": 1,
   "Brawler Gloves + Tombhammer": 1,
   "Crystal Reaper + Hallowfall": 1,
   "Grailseeker + Holy Staff": 1,
   "Demonic Staff + Holy Staff": 1
  },
  "Broadsword + Ironroot Staff": {
   "Blight Staff + Greataxe": 1
  },
  "Fists of Avalon + Holy Staff": {
   "Claymore + Holy Staff": 2,
   "Demonic Staff + Holy Staff": 1,
   "Heavy Crossbow + Holy Staff": 1,
   "Bloodletter + Whispering Bow": 1,
   "Dagger + Staff of Balance": 1,
   "Hellspawn Staff + Holy Staff": 1,
   "Bear Paws + Holy Staff": 1,
   "Battleaxe + Holy Staff": 1
  },
  "Hellfire Hands + Tombhammer": {
   "Fists of Avalon + Holy Staff": 1,
   "Black Monk Stave + Deathgivers": 1,
   "Heavy Crossbow + Holy Staff": 1
  },
  "Battleaxe + Demonic Staff": {
   "Great Fire Staff + Greataxe": 1
  },
  "Battleaxe + Cursed Staff": {
   "Battleaxe + Battleaxe": 1
  },
  "Bear Paws + Bow of Badon": {
   "Bow of Badon + Holy Staff": 1
  },
  "Carrioncaller + Heavy Crossbow": {
   "Cursed Staff + Holy Staff": 1,
   "Bloodletter + Heavy Crossbow": 1,
   "Dagger Pair + Holy Staff": 1
  },
  "Heavy Crossbow + Prowling Staff": {
   "Black Monk Stave + Dagger": 1,
   "Dagger Pair + Glaive": 1,
   "Claymore + Heavy Crossbow": 1
  },
  "Black Monk Stave + Dagger": {
   "Battleaxe + Heron Spear": 1
  },
  "Heavy Crossbow + Warbow": {
   "Heavy Crossbow + Holy Staff": 1
  },
  "Bloodletter + Pike": {
   "Heavy Crossbow + Holy Staff": 1
  },
  "Spirithunter + Tombhammer": {
   "Dagger + Grailseeker": 1
  },
  "Bear Paws + Longbow": {
   "Longbow + Pike": 1
  },
  "Claymore + Hallowfall": {
   "Hellspawn Staff + Holy Staff": 1
  },
  "Battleaxe + Bear Paws": {
   "Bloodletter + Greataxe": 1,
   "Bear Paws + Cursed Staff": 1
  },
  "Bear Paws + Bear Paws": {
   "Battleaxe + Greataxe": 1
  },
  "Greataxe + Warbow": {
   "Longbow + Warbow": 1
  },
  "Hallowfall + Hellspawn Staff": {
   "Dawnsong + Energy Shaper": 1
  },
  "Greataxe + Heron Spear": {
   "Glacial Staff + Staff of Balance": 1
  },
  "Broadsword + Holy Staff": {
   "Bow of Badon + Holy Staff": 1,
   "Ironroot Staff + Kingmaker": 1,
   "Deathgivers + Holy Staff": 1,
   "Dagger Pair + Dagger Pair": 1
  },
  "Bow of Badon + Crystal Reaper": {
   "Bow of Badon + Longbow": 1
  },
  "Crystal Reaper + Heron Spear": {
   "Energy Shaper + Heron Spear": 1
  },
  "Arclight Blasters + Bloodletter": {
   "Bow of Badon + Hallowfall": 1
  },
  "Bloodletter + Carrioncaller": {
   "Claymore + Holy Staff": 1
  },
  "Fists of Avalon + Ironroot Staff": {
   "Battleaxe + Holy Staff": 1
  },
  "Carving Sword + Heavy Crossbow": {
   "Heavy Crossbow + Prowling Staff": 1,
   "Claymore + Holy Staff": 1
  },
  "Dagger Pair + Heavy Crossbow": {
   "Glacial Staff + Staff of Balance": 1
  },
  "Holy Staff + Realmbreaker": {
   "Bow of Badon + Holy Staff": 1
  },
  "Realmbreaker + Redemption Staff": {
   "Battleaxe + Claymore": 1
  },
  "Carving Sword + Hellspawn Staff": {
   "Arclight Blasters + Crystal Reaper": 1
  },
  "Glacial Staff + Staff of Balance": {
   "Bear Paws + Whispering Bow": 1,
   "Heavy Crossbow + Holy Staff": 1,
   "Crystal Reaper + Great Holy Staff": 1,
   "Glaive + Holy Staff": 1,
   "Battleaxe + Wildfire Staff": 1
  },
  "Dagger Pair + Dagger Pair": {
   "Dagger Pair + Soulscythe": 1,
   "Longbow + Longbow": 1
  },
  "Grailseeker + Heron Spear": {
   "Great Fire Staff + Greataxe": 1
  },
  "Claymore + Great Holy Staff": {
   "Grailseeker + Great Fire Staff": 1
  },
  "Bloodletter + Hellspawn Staff": {
   "Arclight Blasters + Cursed Staff": 1
  },
  "Great Fire Staff + Holy Staff": {
   "Dagger Pair + Dagger Pair": 1,
   "Blazing Staff + Twin Slayers": 1
  },
  "Glaive + Holy Staff": {
   "Claymore + Holy Staff": 3,
   "Dagger Pair + Holy Staff": 1,
   "Heavy Crossbow + Holy Staff": 1,
   "Demonic Staff + Holy Staff": 1
  },
  "Claymore + Heavy Crossbow": {
   "Glaive + Holy Staff": 1,
   "Hellspawn Staff + Holy Staff": 1,
   "Carving Sword + Holy Staff": 1
  },
  "Staff of Balance + Wildfire Staff": {
   "Claymore + Holy Staff": 1
  },
  "Arclight Blasters + Mistpiercer": {
   "Grailseeker + Longbow": 1
  },
  "Holy Staff + Longbow": {
   "Infernal Scythe + Redemption Staff": 1
  },
  "Brawler Gloves + Longbow": {
   "Infernal Scythe + Staff of Balance": 1
  },
  "Energy Shaper + Greataxe": {
   "Bow of Badon + Energy Shaper": 1
  },
  "Dagger Pair + Soulscythe": {
   "Bedrock Mace + Glacial Staff": 1
  },
  "Battleaxe + Bow of Badon": {
   "Bear Paws + Whispering Bow": 1,
   "Dagger Pair + Holy Staff": 1
  },
  "Bear Paws + Dagger Pair": {
   "Cursed Staff + Longbow": 1
  },
  "Arclight Blasters + Ironroot Staff": {
   "Carving Sword + Holy Staff": 1
  },
  "Bloodletter + Bow of Badon": {
   "Claymore + Deathgivers": 1,
   "Bow of Badon + Ursine Maulers": 1
  },
  "Holy Staff + Pike": {
   "Hellspawn Staff + Holy Staff": 1
  },
  "Dagger Pair + Greataxe": {
   "Heavy Crossbow + Holy Staff": 1
  },
  "Holy Staff + Lifecurse Staff": {
   "Battleaxe + Holy Staff": 1,
   "Dagger + Staff of Balance": 1
  },
  "Crossbow + Holy Staff": {
   "Claymore + Holy Staff": 1
  },
  "Greataxe + Hellfire Hands": {
   "Holy Staff + Infernal Scythe": 1,
   "Dagger Pair + Grailseeker": 1
  },
  "Battleaxe + Tombhammer": {
   "Bear Paws + Dagger Pair": 1,
   "Dagger Pair + Holy Staff": 1
  },
  "Hellspawn Staff + Redemption Staff": {
   "Energy Shaper + Grailseeker": 1
  },
  "Arclight Blasters + Kingmaker": {
   "Heavy Crossbow + Holy Staff": 1,
   "Bow of Badon + Holy Staff": 1,
   "Bear Paws + Blazing Staff": 1
  },
  "Longbow + Tombhammer": {
   "Bear Paws + Blazing Staff": 1
  },
  "Bow of Badon + Tombhammer": {
   "Warbow + Warbow": 1,
   "Infernal Scythe + Realmbreaker": 1,
   "Bear Paws + Infernal Scythe": 1,
   "Bow of Badon + Holy Staff": 1
  },
  "Fists of Avalon + Staff of Balance": {
   "Claymore + Holy Staff": 1,
   "Hellfire Hands + Holy Staff": 1
  },
  "Brawler Gloves + Heavy Crossbow": {
   "Hellspawn Staff + Holy Staff": 1
  },
  "Brawler Gloves + Tombhammer": {
   "Demonic Staff + Holy Staff": 1,
   "Carrioncaller + Holy Staff": 1
  },
  "Brawler Gloves + Heron Spear": {
   "Demonic Staff + Holy Staff": 1,
   "Dagger Pair + Great Holy Staff": 2,
   "Claymore + Holy Staff": 3,
   "Dagger Pair + Dagger Pair": 1,
   "Warbow + Warbow": 1,
   "Battleaxe + Holy Staff": 1
  },
  "Battleaxe + Fists of Avalon": {
   "Broadsword + Wildfire Staff": 1
  },
  "Carving Sword + Warbow": {
   "Dagger Pair + Dagger Pair": 1
  },
  "Dagger + Energy Shaper": {
   "Holy Staff + Kingmaker": 1
  },
  "Claymore + Dagger Pair": {
   "Cursed Staff + Rotcaller Staff": 1
  },
  "Dagger Pair + Great Holy Staff": {
   "Battleaxe + Bow of Badon": 1
  },
  "Bow of Badon + Heron Spear": {
   "Claymore + Dagger Pair": 1
  },
  "Bear Paws + Bloodletter": {
   "Battleaxe + Warbow": 1
  },
  "Fists of Avalon + Soulscythe": {
   "Bloodletter + Hellfire Hands": 1
  },
  "Blazing Staff + Staff of Balance": {
   "Heavy Crossbow + Holy Staff": 1
  },
  "Holy Staff + Mistpiercer": {
   "Dagger Pair + Dagger Pair": 1
  },
  "Crystal Reaper + Hallowfall": {
   "Heron Spear + Holy Staff": 1,
   "Bear Paws + Infernal Scythe": 1
  },
  "Broadsword + Great Holy Staff": {
   "Hellfire Hands + Holy Staff": 1
  },
  "Crossbow + Greataxe": {
   "Carving Sword + Hallowfall": 1
  },
  "Cursed Staff + Redemption Staff": {
   "Dagger + Heron Spear": 1
  },
  "Bear Paws + Blazing Staff": {
   "Bow of Badon + Brawler Gloves": 1
  },
  "Carving Sword + Longbow": {
   "Blazing Staff + Energy Shaper": 1
  },
  "Bear Paws + Great Holy Staff": {
   "Bear Paws + Longbow": 1
  },
  "Bloodletter + Tombhammer": {
   "Claymore + Holy Staff": 1
  },
  "Crystal Reaper + Longbow": {
   "Claymore + Greataxe": 1
  },
  "Hellspawn Staff + Mistpiercer": {
   "Carving Sword + Holy Staff": 1,
   "Hellfire Hands + Holy Staff": 1
  },
  "Arclight Blasters + Great Holy Staff": {
   "Arclight Blasters + Holy Staff": 2,
   "Claymore + Holy Staff": 1,
   "Demonic Staff + Holy Staff": 1
  },
  "Daybreaker + Holy Staff": {
   "Bear Paws + Holy Staff": 1,
   "Longbow + Redemption Staff": 1
  },
  "Bear Paws + Hellfire Hands": {
   "Bow of Badon + Holy Staff": 1
  },
  "Bloodletter + Heron Spear": {
   "Claymore + Dagger Pair": 1
  },
  "Bow of Badon + Dagger Pair": {
   "Bear Paws + Bow of Badon": 1
  },
  "Heavy Crossbow + Heron Spear": {
   "Deathgivers + Holy Staff": 1
  },
  "Bear Paws + Fists of Avalon": {
   "Brawler Gloves + Cursed Staff": 1
  },
  "Bear Paws + Dawnsong": {
   "Dawnsong + Greataxe": 1
  },
  "Battleaxe + Deathgivers": {
   "Carving Sword + Claymore": 1
  },
  "Dagger Pair + Grailseeker": {
   "Dagger Pair + Lifecurse Staff": 1
  },
  "Fists of Avalon + Heavy Crossbow": {
   "Bear Paws + Holy Staff": 1
  },
  "Heron Spear + Holy Staff": {
   "Greataxe + Tombhammer": 1
  },
  "Fists of Avalon + Warbow": {
   "Bow of Badon + Dagger Pair": 1
  },
  "Carving Sword + Great Holy Staff": {
   "Arclight Blasters + Holy Staff": 1
  },
  "Heavy Crossbow + Tombhammer": {
   "Hellfire Hands + Tombhammer": 1
  }
 }
};
