/* ===========================================================
   Albion Meta - kills counted from the Albion API
   -----------------------------------------------------------
   Written by collect-winrates.py, do not edit by hand.

   "kills" counts how often the first weapon beat the second in
   a fight that looked like a 2v2: one assist, both players
   under 1350 item power, both on a weapon this site lists.

   "duos" is the same fights read as a whole: a pair beating a
   pair, worked out by waiting for both of the losing side to
   die in the same battle. That is the only way to know which
   dps died next to a healer, the event itself never says.

   All three Albion worlds are read, Americas, Europe and Asia,
   and counted together. "regions" is only there to show how
   much each one contributed.

   The API cannot say a kill happened in a hellgate, so this is
   the shape of the fight, not a hellgate flag. Run the script
   often, it only ever sees the last half hour of kills.
   =========================================================== */

window.ALBION_WINRATES = {
 "updated": "2026-09-15T12:38:23+00:00",
 "eventsSeen": 84211,
 "qualifying": 4871,
 "duoFights": 1229,
 "runs": 103,
 "regions": {
  "americas": {
   "events": 35705,
   "kills": 2032,
   "lastSeen": "2026-09-15T12:32:27.009422400Z"
  },
  "europe": {
   "events": 31139,
   "kills": 1994,
   "lastSeen": "2026-09-15T12:32:14.653968300Z"
  },
  "asia": {
   "events": 17367,
   "kills": 845,
   "lastSeen": "2026-09-15T12:32:21.151045900Z"
  }
 },
 "kills": {
  "Carrioncaller": {
   "Dagger": 1,
   "Holy Staff": 58,
   "Grailseeker": 1,
   "Blight Staff": 1,
   "Bloodletter": 6,
   "Crossbow": 3,
   "Brawler Gloves": 4,
   "Whispering Bow": 1,
   "Great Holy Staff": 5,
   "Carving Sword": 5,
   "Ursine Maulers": 1,
   "Infernal Scythe": 1,
   "Cursed Staff": 1,
   "Heavy Crossbow": 8,
   "Bear Paws": 1,
   "Dagger Pair": 12,
   "Claymore": 8,
   "Carrioncaller": 4,
   "Longbow": 3,
   "Demonic Staff": 7,
   "Hellspawn Staff": 4,
   "Prowling Staff": 4,
   "Broadsword": 1,
   "Soulscythe": 2,
   "Fists of Avalon": 5,
   "Arclight Blasters": 4,
   "Realmbreaker": 3,
   "Bow of Badon": 2,
   "Battleaxe": 1,
   "Permafrost Prism": 1,
   "Heron Spear": 1,
   "Glaive": 1,
   "Deathgivers": 3,
   "Pike": 2,
   "Warbow": 1,
   "Kingmaker": 1
  },
  "Deathgivers": {
   "Warbow": 2,
   "Dagger Pair": 4,
   "Cursed Staff": 8,
   "Blight Staff": 1,
   "Greataxe": 5,
   "Bow of Badon": 5,
   "Battleaxe": 9,
   "Claymore": 9,
   "Holy Staff": 24,
   "Carrioncaller": 3,
   "Brawler Gloves": 11,
   "Whispering Bow": 4,
   "Great Fire Staff": 1,
   "Broadsword": 2,
   "Bear Paws": 2,
   "Crossbow": 1,
   "Hellspawn Staff": 2,
   "Staff of Balance": 1,
   "Blazing Staff": 4,
   "Dagger": 1,
   "Carving Sword": 4,
   "Longbow": 5,
   "Lifecurse Staff": 1,
   "Bloodletter": 3,
   "Heavy Crossbow": 5,
   "Mistpiercer": 2,
   "Ursine Maulers": 1,
   "Heron Spear": 5,
   "Deathgivers": 2,
   "Wildfire Staff": 1,
   "Infernal Scythe": 1,
   "Fists of Avalon": 1,
   "Tombhammer": 1,
   "Kingmaker": 1,
   "Daybreaker": 1
  },
  "Dagger Pair": {
   "Holy Staff": 113,
   "Dagger": 4,
   "Longbow": 14,
   "Carrioncaller": 9,
   "Claymore": 27,
   "Bear Paws": 12,
   "Battleaxe": 20,
   "Heavy Crossbow": 20,
   "Hallowfall": 6,
   "Dagger Pair": 17,
   "Rotcaller Staff": 2,
   "Hellspawn Staff": 6,
   "Blight Staff": 3,
   "Great Fire Staff": 2,
   "Bloodletter": 6,
   "Crossbow": 2,
   "Ironroot Staff": 1,
   "Deathgivers": 5,
   "Greataxe": 7,
   "Realmbreaker": 2,
   "Bow of Badon": 7,
   "Wildfire Staff": 5,
   "Infernal Scythe": 2,
   "Energy Shaper": 3,
   "Redemption Staff": 1,
   "Great Holy Staff": 6,
   "Lifecurse Staff": 2,
   "Carving Sword": 3,
   "Staff of Balance": 10,
   "Glacial Staff": 6,
   "Demonic Staff": 7,
   "Soulscythe": 2,
   "Bedrock Mace": 1,
   "Cursed Staff": 9,
   "Whispering Bow": 2,
   "Warbow": 3,
   "Divine Staff": 1,
   "Brawler Gloves": 16,
   "Broadsword": 4,
   "Grailseeker": 4,
   "Kingmaker": 3,
   "Tombhammer": 5,
   "Ursine Maulers": 2,
   "Heron Spear": 5,
   "Arclight Blasters": 1,
   "Hellfire Hands": 2,
   "Pike": 1,
   "Fists of Avalon": 2,
   "Blazing Staff": 2,
   "Glaive": 1
  },
  "Demonic Staff": {
   "Blazing Staff": 3,
   "Claymore": 33,
   "Dagger": 12,
   "Holy Staff": 100,
   "Carrioncaller": 3,
   "Heavy Crossbow": 28,
   "Dagger Pair": 18,
   "Glacial Staff": 4,
   "Great Holy Staff": 1,
   "Prowling Staff": 6,
   "Warbow": 3,
   "Battleaxe": 7,
   "Brawler Gloves": 10,
   "Longbow": 4,
   "Soulscythe": 8,
   "Great Fire Staff": 1,
   "Greataxe": 1,
   "Broadsword": 2,
   "Deathgivers": 4,
   "Bow of Badon": 4,
   "Twin Slayers": 2,
   "Wildfire Staff": 1,
   "Staff of Balance": 11,
   "Carving Sword": 3,
   "Arclight Blasters": 6,
   "Fists of Avalon": 2,
   "Demonic Staff": 9,
   "Pike": 2,
   "Grailseeker": 9,
   "Hellfire Hands": 2,
   "Hellspawn Staff": 3,
   "Whispering Bow": 2,
   "Tombhammer": 2,
   "Hallowfall": 1,
   "Lifecurse Staff": 1,
   "Spirithunter": 1,
   "Glaive": 3,
   "Cursed Staff": 1,
   "Rotcaller Staff": 1,
   "Ironroot Staff": 2,
   "Heron Spear": 1,
   "Realmbreaker": 3,
   "Divine Staff": 1
  },
  "Claymore": {
   "Dagger": 4,
   "Grailseeker": 9,
   "Bloodletter": 11,
   "Heavy Crossbow": 52,
   "Holy Staff": 182,
   "Divine Staff": 4,
   "Claymore": 41,
   "Great Holy Staff": 8,
   "Bow of Badon": 13,
   "Dagger Pair": 38,
   "Cursed Staff": 14,
   "Blight Staff": 6,
   "Demonic Staff": 22,
   "Battleaxe": 21,
   "Hellfire Hands": 13,
   "Greataxe": 10,
   "Tombhammer": 10,
   "Lifecurse Staff": 2,
   "Crossbow": 14,
   "Whispering Bow": 5,
   "Daybreaker": 1,
   "Wildfire Staff": 5,
   "Forcepulse Bracers": 3,
   "Bedrock Mace": 1,
   "Brawler Gloves": 21,
   "Longbow": 12,
   "Warbow": 28,
   "Deathgivers": 9,
   "Hellspawn Staff": 21,
   "Crystal Reaper": 3,
   "Carving Sword": 11,
   "Ironroot Staff": 6,
   "Carrioncaller": 8,
   "Hallowfall": 3,
   "Fists of Avalon": 7,
   "Staff of Balance": 11,
   "Glacial Staff": 6,
   "Soulscythe": 8,
   "Great Fire Staff": 6,
   "Heron Spear": 6,
   "Glaive": 2,
   "Prowling Staff": 4,
   "Realmbreaker": 3,
   "Energy Shaper": 4,
   "Arclight Blasters": 6,
   "Rotcaller Staff": 3,
   "Broadsword": 6,
   "Spirithunter": 2,
   "Infernal Scythe": 2,
   "Kingmaker": 1,
   "Mistpiercer": 1,
   "Redemption Staff": 2,
   "Blazing Staff": 2,
   "Occult Staff": 1,
   "Black Monk Stave": 1,
   "Dawnsong": 1,
   "Twin Slayers": 2,
   "Permafrost Prism": 2,
   "Bear Paws": 2,
   "Pike": 3,
   "Great Arcane Staff": 2
  },
  "Whispering Bow": {
   "Bow of Badon": 6,
   "Cursed Staff": 3,
   "Carrioncaller": 3,
   "Bloodletter": 3,
   "Warbow": 4,
   "Spirithunter": 1,
   "Claymore": 2,
   "Holy Staff": 2,
   "Crossbow": 5,
   "Mistpiercer": 2,
   "Lifecurse Staff": 2,
   "Longbow": 3,
   "Crystal Reaper": 1,
   "Infernal Scythe": 2,
   "Broadsword": 3,
   "Bear Paws": 3,
   "Battleaxe": 6,
   "Kingmaker": 1,
   "Brawler Gloves": 4,
   "Carving Sword": 2,
   "Glacial Staff": 1,
   "Blight Staff": 1,
   "Deathgivers": 1,
   "Hallowfall": 1,
   "Heavy Crossbow": 1,
   "Greataxe": 1,
   "Dagger Pair": 4,
   "Divine Staff": 1,
   "Tombhammer": 1,
   "Fists of Avalon": 1,
   "Hellfire Hands": 1,
   "Whispering Bow": 1,
   "Staff of Balance": 1,
   "Great Holy Staff": 1,
   "Dagger": 1
  },
  "Arclight Blasters": {
   "Demonic Staff": 12,
   "Holy Staff": 69,
   "Hellspawn Staff": 5,
   "Bow of Badon": 22,
   "Energy Shaper": 5,
   "Carrioncaller": 3,
   "Wildfire Staff": 3,
   "Claymore": 16,
   "Arclight Blasters": 15,
   "Great Holy Staff": 10,
   "Heavy Crossbow": 8,
   "Longbow": 5,
   "Realmbreaker": 2,
   "Battleaxe": 12,
   "Greataxe": 7,
   "Ironroot Staff": 4,
   "Deathgivers": 5,
   "Hallowfall": 6,
   "Bloodletter": 1,
   "Mistpiercer": 4,
   "Warbow": 6,
   "Blazing Staff": 5,
   "Bear Paws": 3,
   "Grailseeker": 2,
   "Blight Staff": 1,
   "Carving Sword": 3,
   "Heron Spear": 4,
   "Forcepulse Bracers": 1,
   "Glacial Staff": 2,
   "Tombhammer": 1,
   "Rotcaller Staff": 4,
   "Brawler Gloves": 12,
   "Kingmaker": 1,
   "Dagger Pair": 3,
   "Daybreaker": 2,
   "Crystal Reaper": 2,
   "Twin Slayers": 1,
   "Great Arcane Staff": 1,
   "Lifecurse Staff": 2,
   "Staff of Balance": 3,
   "Spirithunter": 3,
   "Divine Staff": 1,
   "Soulscythe": 2,
   "Whispering Bow": 2,
   "Dawnsong": 1,
   "Prowling Staff": 1,
   "Cursed Staff": 2,
   "Fists of Avalon": 2
  },
  "Greataxe": {
   "Mistpiercer": 2,
   "Battleaxe": 12,
   "Broadsword": 2,
   "Lifecurse Staff": 2,
   "Hallowfall": 4,
   "Bloodletter": 4,
   "Bow of Badon": 7,
   "Great Fire Staff": 3,
   "Blight Staff": 2,
   "Crystal Reaper": 2,
   "Spirithunter": 1,
   "Soulscythe": 1,
   "Hellspawn Staff": 2,
   "Holy Staff": 26,
   "Cursed Staff": 4,
   "Pike": 1,
   "Realmbreaker": 1,
   "Deathgivers": 1,
   "Longbow": 5,
   "Warbow": 4,
   "Redemption Staff": 3,
   "Staff of Balance": 1,
   "Glacial Staff": 2,
   "Fists of Avalon": 3,
   "Dagger": 1,
   "Crossbow": 1,
   "Greataxe": 3,
   "Carrioncaller": 3,
   "Bear Paws": 5,
   "Dagger Pair": 14,
   "Whispering Bow": 2,
   "Heavy Crossbow": 4,
   "Claymore": 8,
   "Infernal Scythe": 2,
   "Grailseeker": 1,
   "Carving Sword": 3,
   "Brawler Gloves": 1,
   "Divine Staff": 1,
   "Tombhammer": 1,
   "Energy Shaper": 1,
   "Wailing Bow": 1,
   "Ironroot Staff": 3,
   "Kingmaker": 1,
   "Great Holy Staff": 4,
   "Prowling Staff": 1,
   "Daybreaker": 1,
   "Arclight Blasters": 3,
   "Rotcaller Staff": 1,
   "Heron Spear": 1,
   "Twin Slayers": 1,
   "Great Arcane Staff": 3,
   "Blazing Staff": 1
  },
  "Forcepulse Bracers": {
   "Arclight Blasters": 1,
   "Holy Staff": 1,
   "Crystal Reaper": 3,
   "Longbow": 1,
   "Claymore": 1,
   "Staff of Balance": 1,
   "Brawler Gloves": 1,
   "Bloodletter": 1
  },
  "Heavy Crossbow": {
   "Carrioncaller": 7,
   "Holy Staff": 98,
   "Grailseeker": 3,
   "Dagger": 4,
   "Bear Paws": 8,
   "Longbow": 9,
   "Greataxe": 11,
   "Heavy Crossbow": 32,
   "Dagger Pair": 15,
   "Warbow": 8,
   "Deathgivers": 8,
   "Claymore": 21,
   "Staff of Balance": 5,
   "Whispering Bow": 4,
   "Fists of Avalon": 5,
   "Broadsword": 4,
   "Cursed Staff": 8,
   "Hellspawn Staff": 11,
   "Brawler Gloves": 11,
   "Great Fire Staff": 2,
   "Pike": 2,
   "Kingmaker": 1,
   "Hallowfall": 3,
   "Great Holy Staff": 3,
   "Carving Sword": 3,
   "Energy Shaper": 1,
   "Hellfire Hands": 12,
   "Tombhammer": 11,
   "Bloodletter": 5,
   "Black Monk Stave": 2,
   "Demonic Staff": 5,
   "Glacial Staff": 3,
   "Battleaxe": 11,
   "Prowling Staff": 1,
   "Glaive": 3,
   "Blazing Staff": 2,
   "Crystal Reaper": 1,
   "Heron Spear": 1,
   "Mistpiercer": 2,
   "Crossbow": 5,
   "Realmbreaker": 2,
   "Blight Staff": 1,
   "Daybreaker": 1,
   "Wailing Bow": 1,
   "Divine Staff": 2,
   "Soulscythe": 3,
   "Wildfire Staff": 1,
   "Arclight Blasters": 1
  },
  "Warbow": {
   "Battleaxe": 4,
   "Cursed Staff": 7,
   "Claymore": 8,
   "Longbow": 7,
   "Holy Staff": 11,
   "Lifecurse Staff": 2,
   "Twin Slayers": 1,
   "Hellfire Hands": 2,
   "Heavy Crossbow": 15,
   "Bow of Badon": 11,
   "Bear Paws": 3,
   "Dawnsong": 1,
   "Mistpiercer": 3,
   "Warbow": 5,
   "Broadsword": 2,
   "Grailseeker": 3,
   "Deathgivers": 3,
   "Carving Sword": 1,
   "Demonic Staff": 2,
   "Blight Staff": 1,
   "Prowling Staff": 1,
   "Dagger Pair": 10,
   "Greataxe": 2,
   "Great Holy Staff": 2,
   "Ursine Maulers": 1,
   "Kingmaker": 2,
   "Fists of Avalon": 3,
   "Hellspawn Staff": 1,
   "Crystal Reaper": 3,
   "Heron Spear": 1,
   "Bloodletter": 4,
   "Carrioncaller": 1,
   "Crossbow": 2,
   "Realmbreaker": 2,
   "Soulscythe": 4,
   "Energy Shaper": 2,
   "Blazing Staff": 2,
   "Wildfire Staff": 9,
   "Tombhammer": 2,
   "Whispering Bow": 1
  },
  "Battleaxe": {
   "Dagger Pair": 17,
   "Cursed Staff": 24,
   "Pike": 5,
   "Battleaxe": 27,
   "Dagger": 3,
   "Greataxe": 6,
   "Warbow": 7,
   "Longbow": 11,
   "Bloodletter": 9,
   "Crossbow": 16,
   "Hellfire Hands": 2,
   "Bow of Badon": 13,
   "Permafrost Prism": 3,
   "Great Fire Staff": 5,
   "Blight Staff": 2,
   "Bear Paws": 6,
   "Mistpiercer": 1,
   "Wildfire Staff": 5,
   "Ursine Maulers": 2,
   "Realmbreaker": 1,
   "Tombhammer": 6,
   "Holy Staff": 46,
   "Ironroot Staff": 5,
   "Heron Spear": 2,
   "Carving Sword": 6,
   "Crystal Reaper": 2,
   "Claymore": 12,
   "Heavy Crossbow": 10,
   "Deathgivers": 7,
   "Hallowfall": 1,
   "Kingmaker": 2,
   "Infernal Scythe": 1,
   "Spirithunter": 1,
   "Hellspawn Staff": 2,
   "Black Monk Stave": 3,
   "Glacial Staff": 2,
   "Whispering Bow": 6,
   "Arclight Blasters": 1,
   "Hoarfrost Staff": 1,
   "Divine Staff": 1,
   "Broadsword": 1,
   "Fists of Avalon": 1,
   "Soulscythe": 1,
   "Carrioncaller": 1,
   "Twin Slayers": 1,
   "Brawler Gloves": 14,
   "Prowling Staff": 2,
   "Icicle Staff": 1,
   "Lifecurse Staff": 2,
   "Energy Shaper": 1,
   "Demonic Staff": 4,
   "Grailseeker": 1
  },
  "Dawnsong": {
   "Holy Staff": 3,
   "Energy Shaper": 1,
   "Crossbow": 1,
   "Dawnsong": 1,
   "Greataxe": 1,
   "Cursed Staff": 1,
   "Bear Paws": 1,
   "Blight Staff": 1
  },
  "Bow of Badon": {
   "Mistpiercer": 5,
   "Crossbow": 2,
   "Bow of Badon": 41,
   "Greataxe": 16,
   "Hellfire Hands": 6,
   "Whispering Bow": 6,
   "Holy Staff": 30,
   "Blazing Staff": 4,
   "Bear Paws": 17,
   "Twin Slayers": 3,
   "Staff of Balance": 1,
   "Glacial Staff": 1,
   "Warbow": 8,
   "Brawler Gloves": 7,
   "Crystal Reaper": 2,
   "Deathgivers": 6,
   "Pike": 1,
   "Demonic Staff": 2,
   "Longbow": 14,
   "Battleaxe": 16,
   "Dagger Pair": 13,
   "Forcepulse Bracers": 1,
   "Broadsword": 6,
   "Tombhammer": 2,
   "Blight Staff": 2,
   "Heron Spear": 4,
   "Infernal Scythe": 6,
   "Grailseeker": 3,
   "Hellspawn Staff": 4,
   "Hallowfall": 4,
   "Kingmaker": 1,
   "Great Holy Staff": 2,
   "Arclight Blasters": 9,
   "Soulscythe": 1,
   "Energy Shaper": 4,
   "Prowling Staff": 3,
   "Spirithunter": 3,
   "Claymore": 8,
   "Heavy Crossbow": 4,
   "Fists of Avalon": 3,
   "Bloodletter": 5,
   "Carrioncaller": 2,
   "Redemption Staff": 2,
   "Realmbreaker": 3,
   "Ursine Maulers": 2,
   "Great Fire Staff": 2,
   "Cursed Staff": 3,
   "Black Monk Stave": 2,
   "Carving Sword": 2,
   "Rotcaller Staff": 1,
   "Bedrock Mace": 1,
   "Dagger": 2,
   "Permafrost Prism": 2,
   "Ironroot Staff": 2,
   "Wildfire Staff": 1,
   "Divine Staff": 1
  },
  "Broadsword": {
   "Cursed Staff": 4,
   "Fists of Avalon": 2,
   "Holy Staff": 9,
   "Battleaxe": 4,
   "Greataxe": 2,
   "Blight Staff": 1,
   "Bow of Badon": 2,
   "Kingmaker": 1,
   "Ironroot Staff": 1,
   "Deathgivers": 2,
   "Claymore": 3,
   "Bear Paws": 2,
   "Divine Staff": 1,
   "Great Holy Staff": 2,
   "Heron Spear": 1,
   "Soulscythe": 1,
   "Dagger Pair": 2,
   "Hellfire Hands": 3,
   "Warbow": 3,
   "Crossbow": 1,
   "Brawler Gloves": 1,
   "Longbow": 1
  },
  "Bear Paws": {
   "Bow of Badon": 16,
   "Holy Staff": 33,
   "Broadsword": 3,
   "Claymore": 6,
   "Dagger Pair": 10,
   "Bloodletter": 14,
   "Hallowfall": 5,
   "Hellspawn Staff": 4,
   "Deathgivers": 7,
   "Mistpiercer": 6,
   "Heavy Crossbow": 4,
   "Crossbow": 5,
   "Hellfire Hands": 1,
   "Great Fire Staff": 1,
   "Longbow": 10,
   "Fists of Avalon": 1,
   "Ironroot Staff": 2,
   "Battleaxe": 28,
   "Bear Paws": 8,
   "Heron Spear": 5,
   "Permafrost Prism": 1,
   "Bedrock Mace": 2,
   "Pike": 2,
   "Greataxe": 11,
   "Whispering Bow": 2,
   "Grailseeker": 2,
   "Infernal Scythe": 4,
   "Blazing Staff": 2,
   "Dagger": 2,
   "Cursed Staff": 5,
   "Arclight Blasters": 4,
   "Demonic Staff": 1,
   "Lifecurse Staff": 1,
   "Blight Staff": 5,
   "Carving Sword": 6,
   "Warbow": 7,
   "Brawler Gloves": 3,
   "Dawnsong": 3,
   "Energy Shaper": 1,
   "Tombhammer": 2,
   "Ursine Maulers": 2,
   "Wildfire Staff": 1,
   "Forcepulse Bracers": 1,
   "Kingmaker": 1,
   "Carrioncaller": 3,
   "Daybreaker": 4
  },
  "Mistpiercer": {
   "Arclight Blasters": 2,
   "Fists of Avalon": 1,
   "Bedrock Mace": 1,
   "Longbow": 3,
   "Infernal Scythe": 2,
   "Bow of Badon": 2,
   "Battleaxe": 5,
   "Grailseeker": 2,
   "Holy Staff": 5,
   "Bloodletter": 2,
   "Dagger Pair": 2,
   "Realmbreaker": 1,
   "Carving Sword": 1,
   "Hellfire Hands": 2,
   "Blight Staff": 2,
   "Greataxe": 2,
   "Cursed Staff": 1,
   "Heavy Crossbow": 1,
   "Warbow": 1,
   "Heron Spear": 1,
   "Hellspawn Staff": 1,
   "Twin Slayers": 1,
   "Mistpiercer": 1,
   "Blazing Staff": 1
  },
  "Holy Staff": {
   "Dagger": 28,
   "Battleaxe": 82,
   "Longbow": 48,
   "Mistpiercer": 16,
   "Claymore": 179,
   "Holy Staff": 768,
   "Heavy Crossbow": 165,
   "Bow of Badon": 95,
   "Bear Paws": 39,
   "Greataxe": 36,
   "Dagger Pair": 142,
   "Cursed Staff": 42,
   "Carrioncaller": 43,
   "Blazing Staff": 26,
   "Arclight Blasters": 44,
   "Carving Sword": 34,
   "Fists of Avalon": 35,
   "Demonic Staff": 76,
   "Hallowfall": 24,
   "Deathgivers": 38,
   "Warbow": 58,
   "Staff of Balance": 44,
   "Whispering Bow": 25,
   "Hellspawn Staff": 63,
   "Hellfire Hands": 31,
   "Energy Shaper": 13,
   "Brawler Gloves": 94,
   "Rotcaller Staff": 5,
   "Bloodletter": 31,
   "Crossbow": 34,
   "Wildfire Staff": 11,
   "Divine Staff": 8,
   "Tombhammer": 45,
   "Great Fire Staff": 14,
   "Blight Staff": 12,
   "Permafrost Prism": 6,
   "Lifecurse Staff": 7,
   "Spirithunter": 9,
   "Soulscythe": 24,
   "Ironroot Staff": 22,
   "Broadsword": 17,
   "Glacial Staff": 17,
   "Daybreaker": 6,
   "Great Holy Staff": 32,
   "Ursine Maulers": 4,
   "Forcepulse Bracers": 4,
   "Realmbreaker": 12,
   "Kingmaker": 13,
   "Twin Slayers": 10,
   "Crystal Reaper": 9,
   "Redemption Staff": 14,
   "Heron Spear": 28,
   "Grailseeker": 28,
   "Dawnsong": 3,
   "Infernal Scythe": 8,
   "Prowling Staff": 19,
   "Pike": 10,
   "Glaive": 11,
   "Black Monk Stave": 1,
   "Icicle Staff": 1,
   "Occult Staff": 2,
   "Wailing Bow": 1,
   "Great Arcane Staff": 6
  },
  "Divine Staff": {
   "Grailseeker": 2,
   "Holy Staff": 5,
   "Heavy Crossbow": 1,
   "Bear Paws": 3,
   "Hallowfall": 1,
   "Dagger Pair": 1,
   "Blight Staff": 2,
   "Cursed Staff": 2,
   "Twin Slayers": 1,
   "Greataxe": 1
  },
  "Dagger": {
   "Holy Staff": 41,
   "Heron Spear": 3,
   "Dagger Pair": 12,
   "Heavy Crossbow": 10,
   "Brawler Gloves": 9,
   "Bow of Badon": 2,
   "Claymore": 10,
   "Fists of Avalon": 1,
   "Hallowfall": 1,
   "Staff of Balance": 3,
   "Cursed Staff": 1,
   "Prowling Staff": 1,
   "Battleaxe": 9,
   "Warbow": 4,
   "Kingmaker": 3,
   "Greataxe": 2,
   "Arclight Blasters": 2,
   "Crossbow": 2,
   "Dagger": 2,
   "Wildfire Staff": 1,
   "Tombhammer": 2,
   "Lifecurse Staff": 1,
   "Demonic Staff": 2,
   "Grailseeker": 2,
   "Carving Sword": 1,
   "Ursine Maulers": 1,
   "Glacial Staff": 3,
   "Longbow": 4,
   "Daybreaker": 1,
   "Realmbreaker": 1,
   "Blight Staff": 1,
   "Black Monk Stave": 1,
   "Hellspawn Staff": 1,
   "Mistpiercer": 1,
   "Crystal Reaper": 1,
   "Divine Staff": 1,
   "Deathgivers": 1
  },
  "Grailseeker": {
   "Claymore": 11,
   "Blight Staff": 2,
   "Lifecurse Staff": 3,
   "Dagger Pair": 9,
   "Holy Staff": 29,
   "Heavy Crossbow": 8,
   "Brawler Gloves": 8,
   "Mistpiercer": 2,
   "Crystal Reaper": 3,
   "Bow of Badon": 7,
   "Greataxe": 6,
   "Cursed Staff": 1,
   "Warbow": 8,
   "Battleaxe": 14,
   "Infernal Scythe": 2,
   "Blazing Staff": 2,
   "Heron Spear": 4,
   "Great Holy Staff": 4,
   "Arclight Blasters": 1,
   "Longbow": 6,
   "Great Fire Staff": 1,
   "Dagger": 2,
   "Crossbow": 3,
   "Hallowfall": 1,
   "Deathgivers": 4,
   "Whispering Bow": 2,
   "Black Monk Stave": 2,
   "Demonic Staff": 2,
   "Grailseeker": 2,
   "Great Arcane Staff": 1,
   "Kingmaker": 1,
   "Bloodletter": 1,
   "Glacial Staff": 3,
   "Staff of Balance": 2,
   "Broadsword": 1,
   "Daybreaker": 1,
   "Realmbreaker": 1,
   "Spirithunter": 1,
   "Tombhammer": 1,
   "Twin Slayers": 1,
   "Bear Paws": 2,
   "Divine Staff": 1
  },
  "Cursed Staff": {
   "Battleaxe": 15,
   "Warbow": 6,
   "Cursed Staff": 2,
   "Longbow": 6,
   "Holy Staff": 10,
   "Lifecurse Staff": 2,
   "Dagger Pair": 8,
   "Brawler Gloves": 5,
   "Hellspawn Staff": 1,
   "Deathgivers": 6,
   "Whispering Bow": 3,
   "Claymore": 3,
   "Wildfire Staff": 2,
   "Hellfire Hands": 2,
   "Dawnsong": 1,
   "Fists of Avalon": 2,
   "Heavy Crossbow": 9,
   "Bow of Badon": 13,
   "Bedrock Mace": 1,
   "Kingmaker": 2,
   "Bloodletter": 5,
   "Great Fire Staff": 1,
   "Spirithunter": 1,
   "Carrioncaller": 2,
   "Blazing Staff": 1,
   "Grailseeker": 1,
   "Broadsword": 3,
   "Hallowfall": 1,
   "Bear Paws": 2,
   "Crystal Reaper": 1,
   "Mistpiercer": 1,
   "Greataxe": 2,
   "Dagger": 1,
   "Heron Spear": 2,
   "Arclight Blasters": 1,
   "Demonic Staff": 3,
   "Tombhammer": 1,
   "Prowling Staff": 1,
   "Blight Staff": 1,
   "Ironroot Staff": 2,
   "Crossbow": 1
  },
  "Brawler Gloves": {
   "Battleaxe": 10,
   "Holy Staff": 77,
   "Bloodletter": 5,
   "Crossbow": 3,
   "Claymore": 18,
   "Heavy Crossbow": 6,
   "Mistpiercer": 1,
   "Prowling Staff": 1,
   "Carving Sword": 3,
   "Hellspawn Staff": 5,
   "Demonic Staff": 9,
   "Longbow": 3,
   "Cursed Staff": 5,
   "Hallowfall": 2,
   "Grailseeker": 2,
   "Bow of Badon": 4,
   "Deathgivers": 5,
   "Blight Staff": 2,
   "Black Monk Stave": 2,
   "Dagger": 5,
   "Fists of Avalon": 3,
   "Great Holy Staff": 6,
   "Staff of Balance": 4,
   "Infernal Scythe": 3,
   "Divine Staff": 2,
   "Carrioncaller": 4,
   "Dagger Pair": 14,
   "Warbow": 4,
   "Glacial Staff": 4,
   "Brawler Gloves": 5,
   "Tombhammer": 5,
   "Crystal Reaper": 1,
   "Greataxe": 3,
   "Permafrost Prism": 1,
   "Ursine Maulers": 1,
   "Spirithunter": 1,
   "Hellfire Hands": 1
  },
  "Carving Sword": {
   "Heron Spear": 2,
   "Bow of Badon": 16,
   "Holy Staff": 43,
   "Arclight Blasters": 4,
   "Carving Sword": 4,
   "Fists of Avalon": 2,
   "Whispering Bow": 4,
   "Blight Staff": 4,
   "Claymore": 5,
   "Tombhammer": 1,
   "Battleaxe": 9,
   "Ursine Maulers": 1,
   "Twin Slayers": 1,
   "Bloodletter": 8,
   "Crossbow": 4,
   "Carrioncaller": 2,
   "Dawnsong": 2,
   "Warbow": 4,
   "Heavy Crossbow": 6,
   "Prowling Staff": 2,
   "Staff of Balance": 4,
   "Blazing Staff": 5,
   "Crystal Reaper": 2,
   "Hellspawn Staff": 2,
   "Deathgivers": 2,
   "Bear Paws": 7,
   "Mistpiercer": 3,
   "Greataxe": 3,
   "Grailseeker": 3,
   "Demonic Staff": 5,
   "Cursed Staff": 6,
   "Dagger Pair": 6,
   "Energy Shaper": 2,
   "Longbow": 6,
   "Lifecurse Staff": 2,
   "Wildfire Staff": 3,
   "Brawler Gloves": 2,
   "Hellfire Hands": 1,
   "Realmbreaker": 1,
   "Permafrost Prism": 1,
   "Hallowfall": 2,
   "Ironroot Staff": 1,
   "Broadsword": 1,
   "Glaive": 1,
   "Great Fire Staff": 1
  },
  "Fists of Avalon": {
   "Heron Spear": 2,
   "Holy Staff": 30,
   "Bow of Badon": 5,
   "Whispering Bow": 2,
   "Warbow": 6,
   "Longbow": 5,
   "Twin Slayers": 1,
   "Hallowfall": 1,
   "Arclight Blasters": 2,
   "Hellfire Hands": 3,
   "Claymore": 4,
   "Demonic Staff": 4,
   "Kingmaker": 1,
   "Heavy Crossbow": 3,
   "Infernal Scythe": 2,
   "Dagger Pair": 8,
   "Blight Staff": 3,
   "Battleaxe": 10,
   "Bear Paws": 3,
   "Prowling Staff": 1,
   "Carving Sword": 3,
   "Bloodletter": 3,
   "Grailseeker": 1,
   "Broadsword": 1,
   "Wildfire Staff": 1,
   "Staff of Balance": 1,
   "Dagger": 3,
   "Hellspawn Staff": 2,
   "Cursed Staff": 4,
   "Brawler Gloves": 3,
   "Crystal Reaper": 1,
   "Crossbow": 2,
   "Energy Shaper": 1,
   "Forcepulse Bracers": 1,
   "Mistpiercer": 1,
   "Ironroot Staff": 2,
   "Daybreaker": 1,
   "Spirithunter": 1,
   "Deathgivers": 1,
   "Great Holy Staff": 1,
   "Tombhammer": 2,
   "Soulscythe": 1,
   "Realmbreaker": 1,
   "Blazing Staff": 1
  },
  "Energy Shaper": {
   "Bear Paws": 2,
   "Warbow": 1,
   "Heron Spear": 2,
   "Mistpiercer": 1,
   "Energy Shaper": 1,
   "Bow of Badon": 5,
   "Holy Staff": 10,
   "Longbow": 1,
   "Deathgivers": 1,
   "Whispering Bow": 1,
   "Kingmaker": 2,
   "Brawler Gloves": 1,
   "Arclight Blasters": 1,
   "Heavy Crossbow": 1,
   "Crystal Reaper": 1,
   "Grailseeker": 1,
   "Claymore": 1,
   "Blight Staff": 1,
   "Demonic Staff": 1,
   "Dagger Pair": 1
  },
  "Tombhammer": {
   "Bear Paws": 6,
   "Bloodletter": 2,
   "Bow of Badon": 6,
   "Holy Staff": 38,
   "Bedrock Mace": 1,
   "Hellfire Hands": 8,
   "Great Holy Staff": 1,
   "Fists of Avalon": 2,
   "Warbow": 3,
   "Black Monk Stave": 2,
   "Deathgivers": 1,
   "Prowling Staff": 1,
   "Grailseeker": 1,
   "Dagger": 1,
   "Arclight Blasters": 4,
   "Hallowfall": 1,
   "Broadsword": 2,
   "Dagger Pair": 8,
   "Twin Slayers": 1,
   "Heron Spear": 3,
   "Blazing Staff": 3,
   "Whispering Bow": 1,
   "Longbow": 3,
   "Demonic Staff": 2,
   "Carrioncaller": 3,
   "Infernal Scythe": 3,
   "Realmbreaker": 1,
   "Crossbow": 3,
   "Brawler Gloves": 8,
   "Claymore": 9,
   "Carving Sword": 2,
   "Heavy Crossbow": 5,
   "Tombhammer": 7,
   "Staff of Balance": 2,
   "Battleaxe": 4,
   "Greataxe": 2,
   "Divine Staff": 1,
   "Daybreaker": 1,
   "Ironroot Staff": 1,
   "Hellspawn Staff": 2
  },
  "Hallowfall": {
   "Lifecurse Staff": 2,
   "Hallowfall": 4,
   "Hellfire Hands": 2,
   "Bow of Badon": 21,
   "Spirithunter": 1,
   "Blazing Staff": 2,
   "Tombhammer": 2,
   "Battleaxe": 3,
   "Ursine Maulers": 1,
   "Bedrock Mace": 1,
   "Holy Staff": 11,
   "Hellspawn Staff": 1,
   "Energy Shaper": 1,
   "Dawnsong": 2,
   "Warbow": 1,
   "Glacial Staff": 1,
   "Dagger Pair": 1,
   "Crossbow": 2,
   "Crystal Reaper": 3,
   "Longbow": 6,
   "Cursed Staff": 2,
   "Bear Paws": 3,
   "Twin Slayers": 2,
   "Heron Spear": 1,
   "Infernal Scythe": 1,
   "Black Monk Stave": 1,
   "Greataxe": 1,
   "Arclight Blasters": 5,
   "Carving Sword": 1,
   "Claymore": 3,
   "Brawler Gloves": 3,
   "Heavy Crossbow": 2,
   "Ironroot Staff": 1,
   "Mistpiercer": 1,
   "Carrioncaller": 1,
   "Wailing Bow": 1,
   "Rotcaller Staff": 1
  },
  "Wildfire Staff": {
   "Cursed Staff": 1,
   "Battleaxe": 3,
   "Claymore": 2,
   "Heavy Crossbow": 4,
   "Dagger Pair": 1,
   "Longbow": 2,
   "Holy Staff": 3,
   "Warbow": 1,
   "Deathgivers": 1,
   "Blazing Staff": 1,
   "Bloodletter": 1,
   "Mistpiercer": 1,
   "Bow of Badon": 1,
   "Carrioncaller": 1,
   "Divine Staff": 1,
   "Wildfire Staff": 1
  },
  "Blight Staff": {
   "Cursed Staff": 3,
   "Longbow": 5,
   "Twin Slayers": 1,
   "Blazing Staff": 2,
   "Battleaxe": 5,
   "Dagger": 1,
   "Bow of Badon": 3,
   "Broadsword": 1,
   "Wildfire Staff": 1,
   "Lifecurse Staff": 2,
   "Brawler Gloves": 1,
   "Bear Paws": 1,
   "Holy Staff": 1,
   "Hellfire Hands": 1,
   "Rotcaller Staff": 1,
   "Warbow": 1,
   "Mistpiercer": 1,
   "Heavy Crossbow": 2,
   "Crossbow": 1
  },
  "Infernal Scythe": {
   "Hellfire Hands": 1,
   "Whispering Bow": 1,
   "Staff of Balance": 1,
   "Glacial Staff": 1,
   "Bow of Badon": 4,
   "Holy Staff": 4,
   "Crossbow": 1,
   "Cursed Staff": 1,
   "Battleaxe": 1,
   "Great Holy Staff": 1,
   "Infernal Scythe": 1,
   "Divine Staff": 1,
   "Redemption Staff": 1,
   "Carving Sword": 1,
   "Heavy Crossbow": 3,
   "Longbow": 2,
   "Fists of Avalon": 1,
   "Grailseeker": 1,
   "Dagger": 1,
   "Wailing Bow": 2
  },
  "Crossbow": {
   "Dagger Pair": 3,
   "Dagger": 1,
   "Infernal Scythe": 1,
   "Great Holy Staff": 2,
   "Battleaxe": 8,
   "Hallowfall": 2,
   "Carrioncaller": 1,
   "Great Fire Staff": 3,
   "Blight Staff": 1,
   "Brawler Gloves": 2,
   "Bear Paws": 3,
   "Cursed Staff": 2,
   "Glaive": 1,
   "Deathgivers": 3,
   "Bow of Badon": 8,
   "Bedrock Mace": 1,
   "Greataxe": 3,
   "Redemption Staff": 1,
   "Claymore": 5,
   "Holy Staff": 17,
   "Wildfire Staff": 1,
   "Carving Sword": 2,
   "Warbow": 1,
   "Hellfire Hands": 1,
   "Bloodletter": 1,
   "Heron Spear": 1,
   "Fists of Avalon": 3,
   "Grailseeker": 1
  },
  "Longbow": {
   "Pike": 2,
   "Holy Staff": 9,
   "Battleaxe": 19,
   "Cursed Staff": 7,
   "Great Fire Staff": 2,
   "Bloodletter": 5,
   "Heavy Crossbow": 3,
   "Crossbow": 4,
   "Dawnsong": 2,
   "Warbow": 3,
   "Bear Paws": 5,
   "Forcepulse Bracers": 1,
   "Longbow": 11,
   "Lifecurse Staff": 2,
   "Dagger Pair": 10,
   "Whispering Bow": 4,
   "Bow of Badon": 13,
   "Energy Shaper": 3,
   "Greataxe": 6,
   "Infernal Scythe": 5,
   "Redemption Staff": 1,
   "Staff of Balance": 2,
   "Carving Sword": 2,
   "Grailseeker": 3,
   "Realmbreaker": 2,
   "Great Holy Staff": 1,
   "Crystal Reaper": 3,
   "Blazing Staff": 6,
   "Mistpiercer": 1,
   "Arclight Blasters": 2,
   "Fists of Avalon": 3,
   "Twin Slayers": 2,
   "Claymore": 2,
   "Hellfire Hands": 1,
   "Tombhammer": 1,
   "Ursine Maulers": 1,
   "Hallowfall": 2,
   "Brawler Gloves": 1,
   "Wildfire Staff": 1,
   "Daybreaker": 1,
   "Spirithunter": 1,
   "Dagger": 1,
   "Ironroot Staff": 1
  },
  "Great Holy Staff": {
   "Greataxe": 12,
   "Battleaxe": 8,
   "Hellfire Hands": 2,
   "Bloodletter": 3,
   "Crossbow": 2,
   "Holy Staff": 40,
   "Longbow": 3,
   "Dagger": 1,
   "Grailseeker": 2,
   "Great Fire Staff": 2,
   "Bear Paws": 1,
   "Bow of Badon": 7,
   "Brawler Gloves": 1,
   "Arclight Blasters": 7,
   "Carving Sword": 2,
   "Carrioncaller": 1,
   "Claymore": 6,
   "Demonic Staff": 3,
   "Lifecurse Staff": 2,
   "Heron Spear": 2,
   "Divine Staff": 1,
   "Ironroot Staff": 1,
   "Warbow": 3,
   "Fists of Avalon": 3,
   "Permafrost Prism": 1,
   "Hellspawn Staff": 3,
   "Great Holy Staff": 2,
   "Heavy Crossbow": 3,
   "Rotcaller Staff": 2,
   "Deathgivers": 1,
   "Staff of Balance": 2,
   "Glacial Staff": 2,
   "Prowling Staff": 1,
   "Mistpiercer": 1,
   "Soulscythe": 3,
   "Realmbreaker": 2,
   "Dagger Pair": 2,
   "Kingmaker": 1
  },
  "Pike": {
   "Bloodletter": 1,
   "Greataxe": 3,
   "Holy Staff": 8,
   "Heavy Crossbow": 2,
   "Whispering Bow": 1,
   "Deathgivers": 3,
   "Cursed Staff": 3,
   "Prowling Staff": 1,
   "Hellspawn Staff": 1,
   "Bear Paws": 2,
   "Claymore": 4,
   "Blight Staff": 1,
   "Energy Shaper": 1,
   "Dagger Pair": 3,
   "Battleaxe": 1,
   "Bow of Badon": 1,
   "Grailseeker": 1
  },
  "Heron Spear": {
   "Lifecurse Staff": 1,
   "Twin Slayers": 2,
   "Warbow": 5,
   "Dagger Pair": 11,
   "Bear Paws": 2,
   "Longbow": 4,
   "Holy Staff": 19,
   "Staff of Balance": 1,
   "Glacial Staff": 1,
   "Grailseeker": 2,
   "Energy Shaper": 2,
   "Hellspawn Staff": 2,
   "Bow of Badon": 3,
   "Great Fire Staff": 1,
   "Greataxe": 5,
   "Claymore": 6,
   "Black Monk Stave": 1,
   "Dawnsong": 2,
   "Hoarfrost Staff": 1,
   "Battleaxe": 5,
   "Fists of Avalon": 1,
   "Infernal Scythe": 1,
   "Crystal Reaper": 1,
   "Deathgivers": 2,
   "Demonic Staff": 2,
   "Blight Staff": 1,
   "Tombhammer": 3,
   "Bloodletter": 6,
   "Great Holy Staff": 2,
   "Cursed Staff": 3,
   "Arclight Blasters": 1,
   "Brawler Gloves": 1,
   "Divine Staff": 1,
   "Crossbow": 2,
   "Spirithunter": 1,
   "Heavy Crossbow": 1,
   "Blazing Staff": 2,
   "Ironroot Staff": 3,
   "Dagger": 1,
   "Mistpiercer": 1,
   "Heron Spear": 1,
   "Hellfire Hands": 1
  },
  "Kingmaker": {
   "Warbow": 2,
   "Bow of Badon": 4,
   "Holy Staff": 11,
   "Claymore": 3,
   "Deathgivers": 1,
   "Blazing Staff": 4,
   "Battleaxe": 3,
   "Bear Paws": 2,
   "Great Fire Staff": 3,
   "Heavy Crossbow": 2,
   "Grailseeker": 1,
   "Dagger": 1,
   "Tombhammer": 2,
   "Cursed Staff": 2,
   "Dagger Pair": 2,
   "Hellspawn Staff": 1,
   "Rotcaller Staff": 1,
   "Mistpiercer": 2,
   "Redemption Staff": 1,
   "Longbow": 2,
   "Fists of Avalon": 1,
   "Greataxe": 2,
   "Crossbow": 1,
   "Dawnsong": 1,
   "Heron Spear": 1,
   "Ironroot Staff": 1,
   "Hallowfall": 2,
   "Demonic Staff": 1
  },
  "Bloodletter": {
   "Infernal Scythe": 1,
   "Great Holy Staff": 2,
   "Cursed Staff": 4,
   "Lifecurse Staff": 1,
   "Hallowfall": 2,
   "Carrioncaller": 1,
   "Great Fire Staff": 1,
   "Blight Staff": 5,
   "Holy Staff": 20,
   "Prowling Staff": 1,
   "Brawler Gloves": 4,
   "Wildfire Staff": 1,
   "Bloodletter": 4,
   "Battleaxe": 13,
   "Great Arcane Staff": 1,
   "Glaive": 1,
   "Heavy Crossbow": 3,
   "Bow of Badon": 2,
   "Claymore": 10,
   "Heron Spear": 1,
   "Arclight Blasters": 1,
   "Longbow": 4,
   "Whispering Bow": 1,
   "Deathgivers": 5,
   "Bear Paws": 2,
   "Grailseeker": 2,
   "Dagger Pair": 4,
   "Carving Sword": 3,
   "Warbow": 9,
   "Mistpiercer": 1,
   "Ursine Maulers": 1,
   "Demonic Staff": 3,
   "Hellspawn Staff": 3,
   "Kingmaker": 1,
   "Blazing Staff": 1,
   "Permafrost Prism": 1,
   "Glacial Staff": 2,
   "Staff of Balance": 1,
   "Wailing Bow": 2,
   "Daybreaker": 2,
   "Fists of Avalon": 1
  },
  "Prowling Staff": {
   "Bow of Badon": 5,
   "Wildfire Staff": 2,
   "Holy Staff": 30,
   "Hellspawn Staff": 3,
   "Brawler Gloves": 2,
   "Blazing Staff": 3,
   "Tombhammer": 2,
   "Arclight Blasters": 5,
   "Kingmaker": 2,
   "Black Monk Stave": 1,
   "Dagger": 1,
   "Warbow": 1,
   "Heavy Crossbow": 10,
   "Fists of Avalon": 1,
   "Staff of Balance": 3,
   "Carrioncaller": 1,
   "Dagger Pair": 2,
   "Glaive": 3,
   "Claymore": 5,
   "Demonic Staff": 2,
   "Carving Sword": 2,
   "Longbow": 1,
   "Broadsword": 1,
   "Cursed Staff": 1,
   "Glacial Staff": 2,
   "Battleaxe": 5,
   "Bloodletter": 1,
   "Great Holy Staff": 4,
   "Prowling Staff": 1
  },
  "Redemption Staff": {
   "Deathgivers": 1,
   "Bow of Badon": 1,
   "Forcepulse Bracers": 1,
   "Carrioncaller": 2,
   "Holy Staff": 3,
   "Heavy Crossbow": 1,
   "Claymore": 2,
   "Battleaxe": 2,
   "Longbow": 2,
   "Crossbow": 3,
   "Hellspawn Staff": 1,
   "Grailseeker": 1,
   "Energy Shaper": 1,
   "Dagger": 2,
   "Heron Spear": 1,
   "Carving Sword": 2,
   "Hallowfall": 2,
   "Bear Paws": 1,
   "Ursine Maulers": 1,
   "Dagger Pair": 1,
   "Bloodletter": 1
  },
  "Crystal Reaper": {
   "Bloodletter": 1,
   "Mistpiercer": 2,
   "Battleaxe": 4,
   "Holy Staff": 7,
   "Warbow": 2,
   "Crystal Reaper": 1,
   "Hallowfall": 2,
   "Twin Slayers": 1,
   "Hellspawn Staff": 1,
   "Bow of Badon": 9,
   "Greataxe": 3,
   "Longbow": 6,
   "Bear Paws": 2,
   "Grailseeker": 1,
   "Energy Shaper": 1,
   "Crossbow": 2,
   "Heron Spear": 2,
   "Infernal Scythe": 1,
   "Blazing Staff": 2,
   "Dagger": 1,
   "Arclight Blasters": 2,
   "Claymore": 2,
   "Carving Sword": 1,
   "Great Holy Staff": 1,
   "Prowling Staff": 2,
   "Heavy Crossbow": 1,
   "Tombhammer": 1
  },
  "Hellspawn Staff": {
   "Holy Staff": 71,
   "Cursed Staff": 8,
   "Claymore": 21,
   "Dagger Pair": 11,
   "Divine Staff": 1,
   "Heavy Crossbow": 9,
   "Carving Sword": 3,
   "Hellspawn Staff": 10,
   "Soulscythe": 4,
   "Spirithunter": 4,
   "Demonic Staff": 4,
   "Blazing Staff": 2,
   "Warbow": 4,
   "Great Holy Staff": 2,
   "Twin Slayers": 3,
   "Bow of Badon": 15,
   "Tombhammer": 8,
   "Bear Paws": 4,
   "Carrioncaller": 6,
   "Longbow": 6,
   "Energy Shaper": 4,
   "Arclight Blasters": 10,
   "Broadsword": 2,
   "Crystal Reaper": 2,
   "Mistpiercer": 5,
   "Grailseeker": 4,
   "Heron Spear": 3,
   "Dagger": 3,
   "Whispering Bow": 2,
   "Brawler Gloves": 7,
   "Staff of Balance": 2,
   "Kingmaker": 1,
   "Battleaxe": 6,
   "Hellfire Hands": 8,
   "Pike": 1,
   "Prowling Staff": 2,
   "Redemption Staff": 2,
   "Infernal Scythe": 1,
   "Greataxe": 5,
   "Fists of Avalon": 4,
   "Realmbreaker": 1,
   "Dawnsong": 1,
   "Occult Staff": 1,
   "Crossbow": 3,
   "Forcepulse Bracers": 1,
   "Daybreaker": 2,
   "Hallowfall": 1
  },
  "Soulscythe": {
   "Whispering Bow": 2,
   "Bear Paws": 2,
   "Claymore": 5,
   "Holy Staff": 28,
   "Battleaxe": 3,
   "Heavy Crossbow": 5,
   "Carrioncaller": 1,
   "Redemption Staff": 1,
   "Longbow": 1,
   "Glacial Staff": 1,
   "Bedrock Mace": 1,
   "Hellfire Hands": 1,
   "Bloodletter": 1,
   "Tombhammer": 1,
   "Heron Spear": 1,
   "Bow of Badon": 1,
   "Dagger Pair": 4,
   "Deathgivers": 2,
   "Cursed Staff": 1,
   "Kingmaker": 1,
   "Soulscythe": 1,
   "Demonic Staff": 1
  },
  "Rotcaller Staff": {
   "Hellspawn Staff": 2,
   "Holy Staff": 12,
   "Blight Staff": 1,
   "Great Holy Staff": 1,
   "Crystal Reaper": 1,
   "Demonic Staff": 1,
   "Kingmaker": 1,
   "Glaive": 1,
   "Carving Sword": 2,
   "Redemption Staff": 1,
   "Carrioncaller": 1,
   "Realmbreaker": 1,
   "Broadsword": 1,
   "Claymore": 3,
   "Longbow": 1,
   "Arclight Blasters": 1,
   "Staff of Balance": 1
  },
  "Spirithunter": {
   "Bear Paws": 1,
   "Claymore": 1,
   "Holy Staff": 4,
   "Battleaxe": 3,
   "Grailseeker": 2,
   "Dagger": 1,
   "Bow of Badon": 1,
   "Twin Slayers": 1,
   "Dagger Pair": 1
  },
  "Blazing Staff": {
   "Mistpiercer": 1,
   "Brawler Gloves": 2,
   "Crystal Reaper": 1,
   "Bow of Badon": 3,
   "Greataxe": 3,
   "Cursed Staff": 2,
   "Battleaxe": 6,
   "Infernal Scythe": 2,
   "Blazing Staff": 1,
   "Heron Spear": 1,
   "Heavy Crossbow": 2,
   "Warbow": 1,
   "Holy Staff": 5,
   "Bloodletter": 2,
   "Tombhammer": 1,
   "Energy Shaper": 1,
   "Arclight Blasters": 1,
   "Great Arcane Staff": 1,
   "Kingmaker": 1,
   "Glacial Staff": 1,
   "Bedrock Mace": 1,
   "Bear Paws": 1
  },
  "Hellfire Hands": {
   "Blight Staff": 2,
   "Realmbreaker": 2,
   "Holy Staff": 39,
   "Forcepulse Bracers": 1,
   "Heavy Crossbow": 5,
   "Warbow": 2,
   "Fists of Avalon": 1,
   "Black Monk Stave": 1,
   "Deathgivers": 1,
   "Prowling Staff": 1,
   "Brawler Gloves": 4,
   "Dagger Pair": 7,
   "Mistpiercer": 1,
   "Arclight Blasters": 2,
   "Bow of Badon": 5,
   "Battleaxe": 4,
   "Crossbow": 3,
   "Hellspawn Staff": 3,
   "Claymore": 6,
   "Carving Sword": 3,
   "Hellfire Hands": 2,
   "Infernal Scythe": 1,
   "Grailseeker": 2,
   "Demonic Staff": 2,
   "Great Holy Staff": 1,
   "Tombhammer": 3,
   "Rotcaller Staff": 1,
   "Bloodletter": 2,
   "Blazing Staff": 1,
   "Crystal Reaper": 1,
   "Hallowfall": 2,
   "Permafrost Prism": 1,
   "Longbow": 3,
   "Ironroot Staff": 2,
   "Heron Spear": 1,
   "Carrioncaller": 3,
   "Greataxe": 1,
   "Cursed Staff": 2
  },
  "Ironroot Staff": {
   "Dagger Pair": 3,
   "Holy Staff": 21,
   "Great Holy Staff": 2,
   "Prowling Staff": 2,
   "Heavy Crossbow": 5,
   "Claymore": 2,
   "Warbow": 3,
   "Brawler Gloves": 6,
   "Bow of Badon": 1,
   "Greataxe": 1,
   "Blight Staff": 2,
   "Deathgivers": 1,
   "Carving Sword": 3,
   "Battleaxe": 1,
   "Dagger": 1,
   "Heron Spear": 3,
   "Whispering Bow": 1,
   "Hellspawn Staff": 3,
   "Blazing Staff": 1,
   "Soulscythe": 2,
   "Realmbreaker": 2,
   "Spirithunter": 2,
   "Crossbow": 2,
   "Demonic Staff": 1,
   "Bloodletter": 1,
   "Glaive": 1,
   "Fists of Avalon": 1
  },
  "Great Fire Staff": {
   "Battleaxe": 2,
   "Dagger Pair": 3,
   "Warbow": 1,
   "Bow of Badon": 2,
   "Dawnsong": 1,
   "Twin Slayers": 1,
   "Blazing Staff": 1,
   "Heron Spear": 1,
   "Holy Staff": 1,
   "Cursed Staff": 1,
   "Longbow": 1,
   "Wildfire Staff": 1,
   "Deathgivers": 1
  },
  "Realmbreaker": {
   "Bow of Badon": 5,
   "Ironroot Staff": 1,
   "Holy Staff": 15,
   "Claymore": 5,
   "Battleaxe": 3,
   "Blazing Staff": 1,
   "Lifecurse Staff": 1,
   "Dagger Pair": 3,
   "Redemption Staff": 1,
   "Cursed Staff": 2,
   "Crystal Reaper": 1,
   "Arclight Blasters": 1,
   "Heron Spear": 1,
   "Deathgivers": 2,
   "Kingmaker": 1,
   "Soulscythe": 1,
   "Blight Staff": 1,
   "Heavy Crossbow": 1
  },
  "Permafrost Prism": {
   "Hellfire Hands": 1,
   "Deathgivers": 1,
   "Bow of Badon": 1,
   "Longbow": 1,
   "Battleaxe": 1,
   "Claymore": 1,
   "Dagger Pair": 1
  },
  "Staff of Balance": {
   "Fists of Avalon": 2,
   "Holy Staff": 38,
   "Claymore": 8,
   "Bloodletter": 3,
   "Staff of Balance": 2,
   "Prowling Staff": 3,
   "Kingmaker": 1,
   "Battleaxe": 8,
   "Crossbow": 2,
   "Glacial Staff": 1,
   "Dagger Pair": 4,
   "Heavy Crossbow": 9,
   "Whispering Bow": 2,
   "Bear Paws": 1,
   "Soulscythe": 1,
   "Carving Sword": 3,
   "Greataxe": 2,
   "Tombhammer": 1,
   "Bow of Badon": 2,
   "Longbow": 2,
   "Wildfire Staff": 4,
   "Broadsword": 1,
   "Lifecurse Staff": 1,
   "Great Holy Staff": 4,
   "Crystal Reaper": 1,
   "Glaive": 1,
   "Hellfire Hands": 1,
   "Hoarfrost Staff": 1,
   "Cursed Staff": 1,
   "Hellspawn Staff": 4,
   "Demonic Staff": 1,
   "Dagger": 1,
   "Deathgivers": 2,
   "Warbow": 2,
   "Rotcaller Staff": 1,
   "Arclight Blasters": 2,
   "Ironroot Staff": 2
  },
  "Glacial Staff": {
   "Bloodletter": 2,
   "Battleaxe": 7,
   "Crossbow": 2,
   "Whispering Bow": 2,
   "Bear Paws": 1,
   "Soulscythe": 1,
   "Holy Staff": 17,
   "Claymore": 4,
   "Longbow": 2,
   "Heavy Crossbow": 3,
   "Great Holy Staff": 2,
   "Crystal Reaper": 1,
   "Glaive": 1,
   "Staff of Balance": 1,
   "Hoarfrost Staff": 1,
   "Wildfire Staff": 3,
   "Hellspawn Staff": 4,
   "Carving Sword": 2,
   "Demonic Staff": 1,
   "Dagger": 1,
   "Fists of Avalon": 1,
   "Dagger Pair": 1,
   "Deathgivers": 1,
   "Prowling Staff": 1,
   "Warbow": 1,
   "Ironroot Staff": 2,
   "Arclight Blasters": 1
  },
  "Twin Slayers": {
   "Hellspawn Staff": 2,
   "Holy Staff": 4,
   "Heavy Crossbow": 1,
   "Redemption Staff": 2,
   "Bear Paws": 2,
   "Bow of Badon": 7,
   "Forcepulse Bracers": 1,
   "Infernal Scythe": 1,
   "Battleaxe": 3,
   "Blight Staff": 1,
   "Arclight Blasters": 1,
   "Wildfire Staff": 1,
   "Greataxe": 1,
   "Warbow": 1,
   "Hallowfall": 1,
   "Crystal Reaper": 1,
   "Great Holy Staff": 1,
   "Lifecurse Staff": 1
  },
  "Grovekeeper": {
   "Great Arcane Staff": 1,
   "Warbow": 1,
   "Bow of Badon": 1
  },
  "Hoarfrost Staff": {
   "Blazing Staff": 1,
   "Crossbow": 1,
   "Greataxe": 1,
   "Heavy Crossbow": 1
  },
  "Wailing Bow": {
   "Great Holy Staff": 2,
   "Dagger Pair": 1,
   "Hellfire Hands": 1,
   "Holy Staff": 3
  },
  "Black Monk Stave": {
   "Battleaxe": 1,
   "Heron Spear": 1,
   "Kingmaker": 1,
   "Divine Staff": 1,
   "Longbow": 1
  },
  "Glaive": {
   "Brawler Gloves": 2,
   "Claymore": 8,
   "Heavy Crossbow": 4,
   "Holy Staff": 24,
   "Dagger Pair": 4,
   "Demonic Staff": 2,
   "Bloodletter": 2,
   "Lifecurse Staff": 1,
   "Arclight Blasters": 3,
   "Bow of Badon": 1,
   "Glaive": 1,
   "Carrioncaller": 2,
   "Prowling Staff": 1,
   "Bear Paws": 1
  },
  "Daybreaker": {
   "Greataxe": 1,
   "Warbow": 1,
   "Battleaxe": 2,
   "Claymore": 1,
   "Crystal Reaper": 1,
   "Bear Paws": 2,
   "Holy Staff": 1,
   "Redemption Staff": 1,
   "Longbow": 3,
   "Bow of Badon": 2,
   "Whispering Bow": 1,
   "Cursed Staff": 1,
   "Blight Staff": 1,
   "Daybreaker": 2
  },
  "Lifecurse Staff": {
   "Holy Staff": 4,
   "Heavy Crossbow": 2,
   "Battleaxe": 1,
   "Staff of Balance": 1,
   "Dagger": 1,
   "Realmbreaker": 1,
   "Cursed Staff": 3,
   "Dagger Pair": 2,
   "Hellfire Hands": 2,
   "Tombhammer": 1,
   "Whispering Bow": 1,
   "Longbow": 3,
   "Broadsword": 1,
   "Warbow": 4,
   "Claymore": 2,
   "Bow of Badon": 1,
   "Deathgivers": 1,
   "Divine Staff": 1,
   "Infernal Scythe": 1
  },
  "Occult Staff": {
   "Occult Staff": 2
  },
  "Ursine Maulers": {
   "Arclight Blasters": 2,
   "Bow of Badon": 1,
   "Holy Staff": 1,
   "Longbow": 2,
   "Kingmaker": 1,
   "Hellfire Hands": 1,
   "Carving Sword": 1,
   "Bear Paws": 1,
   "Battleaxe": 1,
   "Deathgivers": 1
  },
  "Bedrock Mace": {
   "Broadsword": 1,
   "Blazing Staff": 1
  },
  "Icicle Staff": {
   "Arclight Blasters": 1
  },
  "Great Arcane Staff": {
   "Carrioncaller": 3,
   "Holy Staff": 10,
   "Battleaxe": 2,
   "Greataxe": 1,
   "Ironroot Staff": 1,
   "Dagger Pair": 2,
   "Fists of Avalon": 1,
   "Kingmaker": 1
  }
 },
 "duos": {
  "Energy Shaper + Tombhammer": {
   "Bear Paws + Bear Paws": 1,
   "Arclight Blasters + Holy Staff": 1
  },
  "Claymore + Holy Staff": {
   "Claymore + Holy Staff": 25,
   "Heavy Crossbow + Holy Staff": 21,
   "Dagger Pair + Holy Staff": 6,
   "Demonic Staff + Holy Staff": 15,
   "Hellfire Hands + Tombhammer": 2,
   "Bow of Badon + Lifecurse Staff": 1,
   "Bloodletter + Crossbow": 2,
   "Holy Staff + Wildfire Staff": 1,
   "Cursed Staff + Holy Staff": 4,
   "Crossbow + Crossbow": 1,
   "Brawler Gloves + Longbow": 2,
   "Brawler Gloves + Crossbow": 1,
   "Demonic Staff + Ironroot Staff": 1,
   "Carrioncaller + Holy Staff": 5,
   "Heavy Crossbow + Heavy Crossbow": 2,
   "Warbow + Warbow": 11,
   "Hellfire Hands + Holy Staff": 3,
   "Fists of Avalon + Holy Staff": 4,
   "Claymore + Ironroot Staff": 1,
   "Glacial Staff + Staff of Balance": 6,
   "Dagger Pair + Soulscythe": 5,
   "Brawler Gloves + Dagger Pair": 1,
   "Demonic Staff + Great Holy Staff": 1,
   "Battleaxe + Holy Staff": 3,
   "Dagger Pair + Dagger Pair": 3,
   "Hellspawn Staff + Holy Staff": 10,
   "Great Fire Staff + Holy Staff": 1,
   "Carving Sword + Holy Staff": 5,
   "Holy Staff + Prowling Staff": 2,
   "Dagger Pair + Ironroot Staff": 1,
   "Grailseeker + Great Fire Staff": 1,
   "Holy Staff + Realmbreaker": 1,
   "Carrioncaller + Longbow": 1,
   "Dagger Pair + Hellfire Hands": 1,
   "Carrioncaller + Hellfire Hands": 1,
   "Greataxe + Hellfire Hands": 1,
   "Arclight Blasters + Holy Staff": 4,
   "Dagger Pair + Great Holy Staff": 2,
   "Dagger Pair + Divine Staff": 1,
   "Brawler Gloves + Heavy Crossbow": 1,
   "Brawler Gloves + Heron Spear": 1,
   "Broadsword + Holy Staff": 4,
   "Whispering Bow + Whispering Bow": 1,
   "Glaive + Holy Staff": 1,
   "Battleaxe + Ironroot Staff": 1,
   "Dagger Pair + Warbow": 1,
   "Battleaxe + Forcepulse Bracers": 1,
   "Kingmaker + Wildfire Staff": 1,
   "Blazing Staff + Redemption Staff": 1,
   "Bow of Badon + Tombhammer": 1,
   "Great Holy Staff + Hellspawn Staff": 1,
   "Crystal Reaper + Hallowfall": 1,
   "Carrioncaller + Great Holy Staff": 1,
   "Infernal Scythe + Staff of Balance": 1,
   "Fists of Avalon + Longbow": 1,
   "Longbow + Tombhammer": 1,
   "Crossbow + Tombhammer": 1,
   "Dagger + Tombhammer": 1,
   "Bloodletter + Brawler Gloves": 2,
   "Deathgivers + Holy Staff": 4,
   "Brawler Gloves + Tombhammer": 1,
   "Claymore + Permafrost Prism": 1,
   "Bloodletter + Permafrost Prism": 1,
   "Tombhammer + Whispering Bow": 1,
   "Battleaxe + Fists of Avalon": 1,
   "Holy Staff + Twin Slayers": 1,
   "Battleaxe + Blight Staff": 1,
   "Claymore + Crossbow": 1,
   "Greataxe + Staff of Balance": 1,
   "Brawler Gloves + Holy Staff": 2,
   "Energy Shaper + Pike": 1,
   "Great Holy Staff + Heavy Crossbow": 1,
   "Bow of Badon + Greataxe": 1,
   "Realmbreaker + Soulscythe": 1,
   "Ironroot Staff + Prowling Staff": 1,
   "Holy Staff + Pike": 1,
   "Cursed Staff + Hellspawn Staff": 1,
   "Great Holy Staff + Greataxe": 1,
   "Dagger Pair + Heavy Crossbow": 2,
   "Claymore + Redemption Staff": 1,
   "Claymore + Fists of Avalon": 1,
   "Holy Staff + Rotcaller Staff": 1
  },
  "Greataxe + Hallowfall": {
   "Hallowfall + Lifecurse Staff": 1,
   "Arclight Blasters + Rotcaller Staff": 1
  },
  "Heavy Crossbow + Holy Staff": {
   "Bear Paws + Longbow": 1,
   "Heavy Crossbow + Holy Staff": 4,
   "Deathgivers + Holy Staff": 3,
   "Staff of Balance + Whispering Bow": 1,
   "Claymore + Holy Staff": 6,
   "Hellspawn Staff + Holy Staff": 3,
   "Hallowfall + Kingmaker": 1,
   "Carrioncaller + Holy Staff": 2,
   "Brawler Gloves + Warbow": 1,
   "Heavy Crossbow + Heavy Crossbow": 2,
   "Cursed Staff + Holy Staff": 1,
   "Dagger Pair + Holy Staff": 4,
   "Demonic Staff + Holy Staff": 2,
   "Bear Paws + Claymore": 1,
   "Battleaxe + Holy Staff": 1,
   "Greataxe + Hellfire Hands": 1,
   "Longbow + Warbow": 1,
   "Warbow + Warbow": 2,
   "Brawler Gloves + Heron Spear": 1,
   "Brawler Gloves + Heavy Crossbow": 1,
   "Hellfire Hands + Holy Staff": 1,
   "Bloodletter + Tombhammer": 1,
   "Holy Staff + Mistpiercer": 1,
   "Dagger + Tombhammer": 1,
   "Battleaxe + Hallowfall": 1,
   "Brawler Gloves + Brawler Gloves": 1,
   "Bloodletter + Brawler Gloves": 1,
   "Deathgivers + Demonic Staff": 1,
   "Battleaxe + Fists of Avalon": 1,
   "Carrioncaller + Great Holy Staff": 1,
   "Fists of Avalon + Longbow": 1,
   "Glaive + Holy Staff": 1,
   "Dagger Pair + Soulscythe": 2
  },
  "Cursed Staff + Warbow": {
   "Cursed Staff + Longbow": 1
  },
  "Carving Sword + Holy Staff": {
   "Bow of Badon + Holy Staff": 3,
   "Carving Sword + Holy Staff": 1,
   "Arclight Blasters + Holy Staff": 1,
   "Blazing Staff + Staff of Balance": 1,
   "Heavy Crossbow + Holy Staff": 1,
   "Deathgivers + Holy Staff": 1,
   "Grailseeker + Mistpiercer": 1,
   "Battleaxe + Holy Staff": 4,
   "Demonic Staff + Holy Staff": 5,
   "Holy Staff + Prowling Staff": 1,
   "Holy Staff + Longbow": 1,
   "Bloodletter + Crossbow": 1,
   "Lifecurse Staff + Staff of Balance": 1,
   "Warbow + Wildfire Staff": 1,
   "Bow of Badon + Warbow": 1,
   "Dagger Pair + Holy Staff": 3,
   "Fists of Avalon + Hellspawn Staff": 1,
   "Claymore + Holy Staff": 1,
   "Glaive + Holy Staff": 1,
   "Holy Staff + Whispering Bow": 1,
   "Greataxe + Holy Staff": 1
  },
  "Dagger Pair + Holy Staff": {
   "Carrioncaller + Holy Staff": 4,
   "Claymore + Holy Staff": 5,
   "Bear Paws + Holy Staff": 2,
   "Heavy Crossbow + Holy Staff": 7,
   "Holy Staff + Rotcaller Staff": 1,
   "Dagger Pair + Dagger Pair": 1,
   "Hellspawn Staff + Holy Staff": 4,
   "Blight Staff + Great Fire Staff": 2,
   "Dagger Pair + Holy Staff": 6,
   "Claymore + Ironroot Staff": 1,
   "Deathgivers + Holy Staff": 3,
   "Greataxe + Holy Staff": 2,
   "Battleaxe + Holy Staff": 3,
   "Demonic Staff + Holy Staff": 3,
   "Dagger Pair + Great Holy Staff": 1,
   "Crossbow + Holy Staff": 1,
   "Cursed Staff + Holy Staff": 1,
   "Tombhammer + Tombhammer": 1,
   "Glacial Staff + Staff of Balance": 2,
   "Claymore + Great Holy Staff": 1,
   "Heavy Crossbow + Longbow": 1,
   "Bear Paws + Carrioncaller": 1,
   "Brawler Gloves + Fists of Avalon": 1,
   "Broadsword + Holy Staff": 1,
   "Dagger Pair + Greataxe": 1,
   "Dagger + Staff of Balance": 2,
   "Brawler Gloves + Ursine Maulers": 1,
   "Dagger + Grailseeker": 1
  },
  "Bow of Badon + Holy Staff": {
   "Bear Paws + Blazing Staff": 1,
   "Brawler Gloves + Mistpiercer": 1,
   "Bow of Badon + Dagger Pair": 1,
   "Holy Staff + Holy Staff": 1,
   "Crystal Reaper + Twin Slayers": 1,
   "Grailseeker + Mistpiercer": 1,
   "Hellspawn Staff + Holy Staff": 1,
   "Deathgivers + Greataxe": 1,
   "Holy Staff + Longbow": 1,
   "Battleaxe + Heavy Crossbow": 1,
   "Dagger Pair + Dagger Pair": 1,
   "Blazing Staff + Redemption Staff": 1,
   "Hallowfall + Heavy Crossbow": 1,
   "Bear Paws + Brawler Gloves": 1,
   "Great Fire Staff + Holy Staff": 1,
   "Cursed Staff + Holy Staff": 1,
   "Bear Paws + Greataxe": 1,
   "Black Monk Stave + Longbow": 1,
   "Bow of Badon + Hellfire Hands": 1,
   "Bear Paws + Cursed Staff": 1,
   "Bow of Badon + Greataxe": 1
  },
  "Bow of Badon + Warbow": {
   "Hellfire Hands + Twin Slayers": 1,
   "Battleaxe + Holy Staff": 1,
   "Demonic Staff + Holy Staff": 1,
   "Claymore + Holy Staff": 1,
   "Bow of Badon + Dagger Pair": 1
  },
  "Bear Paws + Holy Staff": {
   "Claymore + Holy Staff": 1,
   "Bow of Badon + Holy Staff": 2,
   "Hellspawn Staff + Ironroot Staff": 1,
   "Grailseeker + Mistpiercer": 1,
   "Battleaxe + Holy Staff": 1,
   "Bloodletter + Crossbow": 1,
   "Cursed Staff + Ironroot Staff": 1,
   "Bow of Badon + Claymore": 1,
   "Arclight Blasters + Holy Staff": 2,
   "Greataxe + Hallowfall": 1,
   "Holy Staff + Kingmaker": 1,
   "Carrioncaller + Holy Staff": 3,
   "Crossbow + Warbow": 2,
   "Dagger Pair + Holy Staff": 2,
   "Bear Paws + Holy Staff": 1,
   "Daybreaker + Infernal Scythe": 2
  },
  "Bow of Badon + Infernal Scythe": {
   "Glacial Staff + Staff of Balance": 1
  },
  "Dagger Pair + Divine Staff": {
   "Heavy Crossbow + Holy Staff": 1,
   "Bear Paws + Holy Staff": 1,
   "Bear Paws + Cursed Staff": 1
  },
  "Holy Staff + Kingmaker": {
   "Bow of Badon + Warbow": 1,
   "Claymore + Holy Staff": 1,
   "Deathgivers + Holy Staff": 1,
   "Dagger + Grailseeker": 1,
   "Claymore + Tombhammer": 1,
   "Battleaxe + Dagger Pair": 1,
   "Fists of Avalon + Warbow": 1,
   "Bow of Badon + Hallowfall": 1
  },
  "Dagger + Grailseeker": {
   "Heavy Crossbow + Holy Staff": 3,
   "Bow of Badon + Brawler Gloves": 1,
   "Dagger Pair + Holy Staff": 1,
   "Claymore + Holy Staff": 5,
   "Brawler Gloves + Heron Spear": 1,
   "Demonic Staff + Holy Staff": 2,
   "Dagger Pair + Grailseeker": 1,
   "Glacial Staff + Staff of Balance": 1,
   "Brawler Gloves + Holy Staff": 1,
   "Claymore + Heavy Crossbow": 2,
   "Mistpiercer + Tombhammer": 1,
   "Dagger + Grailseeker": 1,
   "Battleaxe + Longbow": 2,
   "Crystal Reaper + Divine Staff": 1
  },
  "Arclight Blasters + Holy Staff": {
   "Bow of Badon + Bow of Badon": 1,
   "Carrioncaller + Holy Staff": 2,
   "Claymore + Holy Staff": 8,
   "Claymore + Great Holy Staff": 3,
   "Longbow + Realmbreaker": 1,
   "Battleaxe + Bow of Badon": 4,
   "Arclight Blasters + Ironroot Staff": 1,
   "Demonic Staff + Holy Staff": 5,
   "Claymore + Ironroot Staff": 1,
   "Bow of Badon + Greataxe": 1,
   "Deathgivers + Holy Staff": 2,
   "Heavy Crossbow + Warbow": 1,
   "Holy Staff + Wildfire Staff": 1,
   "Bear Paws + Holy Staff": 1,
   "Battleaxe + Holy Staff": 1,
   "Heavy Crossbow + Holy Staff": 3,
   "Holy Staff + Longbow": 1,
   "Glacial Staff + Ironroot Staff": 1,
   "Brawler Gloves + Heron Spear": 2,
   "Holy Staff + Kingmaker": 1,
   "Bear Paws + Warbow": 1,
   "Hellspawn Staff + Holy Staff": 1,
   "Dagger Pair + Holy Staff": 3,
   "Arclight Blasters + Great Holy Staff": 1,
   "Carving Sword + Great Holy Staff": 1,
   "Brawler Gloves + Brawler Gloves": 1,
   "Glacial Staff + Staff of Balance": 1,
   "Energy Shaper + Energy Shaper": 1,
   "Divine Staff + Spirithunter": 1,
   "Arclight Blasters + Holy Staff": 1,
   "Battleaxe + Daybreaker": 1,
   "Carving Sword + Holy Staff": 1,
   "Holy Staff + Prowling Staff": 1,
   "Realmbreaker + Soulscythe": 1,
   "Demonic Staff + Great Holy Staff": 2,
   "Greataxe + Holy Staff": 2,
   "Arclight Blasters + Staff of Balance": 1
  },
  "Hellspawn Staff + Holy Staff": {
   "Cursed Staff + Holy Staff": 3,
   "Claymore + Holy Staff": 13,
   "Dagger Pair + Divine Staff": 1,
   "Heavy Crossbow + Holy Staff": 1,
   "Hellspawn Staff + Holy Staff": 4,
   "Demonic Staff + Holy Staff": 4,
   "Dagger Pair + Holy Staff": 5,
   "Dagger Pair + Soulscythe": 1,
   "Great Holy Staff + Hellspawn Staff": 1,
   "Arclight Blasters + Holy Staff": 4,
   "Broadsword + Holy Staff": 1,
   "Soulscythe + Twin Slayers": 1,
   "Arclight Blasters + Crystal Reaper": 1,
   "Grailseeker + Mistpiercer": 1,
   "Bear Paws + Bow of Badon": 1,
   "Dagger + Grailseeker": 1,
   "Carrioncaller + Heavy Crossbow": 1,
   "Bear Paws + Claymore": 1,
   "Carrioncaller + Holy Staff": 3,
   "Dagger + Staff of Balance": 1,
   "Brawler Gloves + Heron Spear": 1,
   "Holy Staff + Prowling Staff": 1,
   "Bow of Badon + Holy Staff": 1,
   "Bow of Badon + Redemption Staff": 1,
   "Heavy Crossbow + Tombhammer": 1,
   "Battleaxe + Holy Staff": 1,
   "Longbow + Tombhammer": 1,
   "Brawler Gloves + Fists of Avalon": 1,
   "Fists of Avalon + Holy Staff": 1,
   "Bear Paws + Crossbow": 1,
   "Hellfire Hands + Tombhammer": 3,
   "Energy Shaper + Soulscythe": 1,
   "Crossbow + Holy Staff": 1
  },
  "Holy Staff + Rotcaller Staff": {
   "Hellspawn Staff + Holy Staff": 2,
   "Crystal Reaper + Holy Staff": 1,
   "Demonic Staff + Holy Staff": 1,
   "Holy Staff + Kingmaker": 1,
   "Glaive + Holy Staff": 1,
   "Carrioncaller + Holy Staff": 1,
   "Claymore + Holy Staff": 2,
   "Carving Sword + Longbow": 1
  },
  "Battleaxe + Holy Staff": {
   "Bloodletter + Crossbow": 1,
   "Bow of Badon + Permafrost Prism": 1,
   "Longbow + Longbow": 1,
   "Dagger Pair + Mistpiercer": 1,
   "Carving Sword + Holy Staff": 2,
   "Claymore + Holy Staff": 2,
   "Bow of Badon + Holy Staff": 1,
   "Deathgivers + Hellspawn Staff": 1,
   "Battleaxe + Holy Staff": 1,
   "Fists of Avalon + Soulscythe": 1,
   "Dagger Pair + Holy Staff": 2,
   "Heavy Crossbow + Wildfire Staff": 1,
   "Cursed Staff + Holy Staff": 2,
   "Heavy Crossbow + Tombhammer": 1,
   "Holy Staff + Prowling Staff": 1,
   "Deathgivers + Icicle Staff": 1,
   "Deathgivers + Holy Staff": 2,
   "Cursed Staff + Longbow": 1,
   "Brawler Gloves + Brawler Gloves": 1,
   "Crossbow + Whispering Bow": 1,
   "Brawler Gloves + Dagger Pair": 1,
   "Crossbow + Holy Staff": 6,
   "Demonic Staff + Holy Staff": 2,
   "Dagger + Grailseeker": 1
  },
  "Cursed Staff + Holy Staff": {
   "Dagger Pair + Holy Staff": 1,
   "Hellspawn Staff + Holy Staff": 1,
   "Lifecurse Staff + Whispering Bow": 1,
   "Fists of Avalon + Heavy Crossbow": 1,
   "Heavy Crossbow + Warbow": 1,
   "Heavy Crossbow + Holy Staff": 1,
   "Grailseeker + Kingmaker": 1,
   "Bow of Badon + Claymore": 1,
   "Tombhammer + Whispering Bow": 1
  },
  "Bloodletter + Crossbow": {
   "Carrioncaller + Hallowfall": 1,
   "Blight Staff + Great Fire Staff": 1,
   "Battleaxe + Holy Staff": 1,
   "Claymore + Holy Staff": 1
  },
  "Greataxe + Holy Staff": {
   "Blight Staff + Great Fire Staff": 1,
   "Soulscythe + Spirithunter": 1,
   "Hellspawn Staff + Holy Staff": 2,
   "Battleaxe + Bloodletter": 1,
   "Longbow + Redemption Staff": 1,
   "Claymore + Holy Staff": 2,
   "Dagger Pair + Dagger Pair": 2,
   "Arclight Blasters + Great Holy Staff": 2
  },
  "Soulscythe + Spirithunter": {
   "Bear Paws + Claymore": 1,
   "Battleaxe + Holy Staff": 1,
   "Dagger Pair + Holy Staff": 1
  },
  "Blazing Staff + Grailseeker": {
   "Brawler Gloves + Mistpiercer": 1,
   "Bow of Badon + Crystal Reaper": 1,
   "Battleaxe + Infernal Scythe": 1
  },
  "Demonic Staff + Holy Staff": {
   "Dagger Pair + Dagger Pair": 1,
   "Claymore + Holy Staff": 22,
   "Heavy Crossbow + Holy Staff": 4,
   "Battleaxe + Holy Staff": 2,
   "Brawler Gloves + Holy Staff": 1,
   "Holy Staff + Longbow": 1,
   "Broadsword + Holy Staff": 2,
   "Brawler Gloves + Brawler Gloves": 1,
   "Dagger Pair + Holy Staff": 9,
   "Deathgivers + Holy Staff": 4,
   "Staff of Balance + Wildfire Staff": 1,
   "Carving Sword + Holy Staff": 2,
   "Arclight Blasters + Holy Staff": 4,
   "Demonic Staff + Holy Staff": 4,
   "Fists of Avalon + Staff of Balance": 1,
   "Pike + Pike": 1,
   "Dagger + Grailseeker": 5,
   "Holy Staff + Prowling Staff": 1,
   "Glacial Staff + Staff of Balance": 3,
   "Claymore + Claymore": 1,
   "Dagger Pair + Heavy Crossbow": 1,
   "Hellspawn Staff + Holy Staff": 2,
   "Dagger Pair + Demonic Staff": 1,
   "Tombhammer + Warbow": 1,
   "Holy Staff + Lifecurse Staff": 1,
   "Tombhammer + Whispering Bow": 1,
   "Soulscythe + Spirithunter": 1,
   "Glaive + Holy Staff": 2,
   "Cursed Staff + Holy Staff": 1,
   "Holy Staff + Rotcaller Staff": 1,
   "Demonic Staff + Ironroot Staff": 1,
   "Brawler Gloves + Heron Spear": 1,
   "Ironroot Staff + Prowling Staff": 1,
   "Carrioncaller + Holy Staff": 1,
   "Battleaxe + Battleaxe": 1
  },
  "Brawler Gloves + Dagger Pair": {
   "Bloodletter + Crossbow": 1,
   "Claymore + Holy Staff": 1,
   "Demonic Staff + Holy Staff": 1,
   "Infernal Scythe + Staff of Balance": 1,
   "Brawler Gloves + Cursed Staff": 1,
   "Glacial Staff + Staff of Balance": 1
  },
  "Deathgivers + Holy Staff": {
   "Claymore + Holy Staff": 4,
   "Carrioncaller + Holy Staff": 2,
   "Brawler Gloves + Whispering Bow": 1,
   "Blazing Staff + Staff of Balance": 1,
   "Carving Sword + Holy Staff": 1,
   "Brawler Gloves + Longbow": 1,
   "Holy Staff + Lifecurse Staff": 1,
   "Heavy Crossbow + Heron Spear": 1,
   "Battleaxe + Bow of Badon": 1,
   "Bloodletter + Brawler Gloves": 1,
   "Hellspawn Staff + Holy Staff": 1,
   "Brawler Gloves + Brawler Gloves": 1,
   "Cursed Staff + Holy Staff": 1,
   "Broadsword + Holy Staff": 1,
   "Infernal Scythe + Whispering Bow": 1,
   "Fists of Avalon + Tombhammer": 1,
   "Holy Staff + Kingmaker": 1,
   "Daybreaker + Holy Staff": 1,
   "Brawler Gloves + Heron Spear": 2,
   "Battleaxe + Holy Staff": 1
  },
  "Claymore + Ironroot Staff": {
   "Dagger Pair + Holy Staff": 2,
   "Brawler Gloves + Warbow": 1,
   "Deathgivers + Holy Staff": 1,
   "Carving Sword + Holy Staff": 1,
   "Warbow + Warbow": 1,
   "Hellspawn Staff + Holy Staff": 1
  },
  "Brawler Gloves + Whispering Bow": {
   "Claymore + Holy Staff": 1,
   "Bloodletter + Crossbow": 1,
   "Blight Staff + Infernal Scythe": 1
  },
  "Carrioncaller + Holy Staff": {
   "Bloodletter + Crossbow": 2,
   "Bear Paws + Holy Staff": 1,
   "Carrioncaller + Holy Staff": 4,
   "Demonic Staff + Holy Staff": 6,
   "Hellspawn Staff + Holy Staff": 4,
   "Claymore + Great Holy Staff": 1,
   "Dagger Pair + Holy Staff": 3,
   "Heavy Crossbow + Holy Staff": 5,
   "Carving Sword + Holy Staff": 2,
   "Dagger Pair + Dagger Pair": 2,
   "Fists of Avalon + Soulscythe": 1,
   "Arclight Blasters + Great Holy Staff": 2,
   "Claymore + Holy Staff": 5,
   "Holy Staff + Prowling Staff": 2,
   "Bloodletter + Brawler Gloves": 1,
   "Arclight Blasters + Holy Staff": 1,
   "Battleaxe + Holy Staff": 1,
   "Bloodletter + Dagger Pair": 1,
   "Heron Spear + Longbow": 1,
   "Fists of Avalon + Realmbreaker": 2,
   "Glaive + Holy Staff": 1,
   "Holy Staff + Pike": 2,
   "Crossbow + Warbow": 1
  },
  "Realmbreaker + Tombhammer": {
   "Bow of Badon + Bow of Badon": 1
  },
  "Bloodletter + Brawler Gloves": {
   "Holy Staff + Prowling Staff": 1,
   "Demonic Staff + Holy Staff": 2,
   "Brawler Gloves + Permafrost Prism": 1,
   "Carving Sword + Holy Staff": 1,
   "Glacial Staff + Staff of Balance": 1,
   "Claymore + Holy Staff": 2,
   "Deathgivers + Great Holy Staff": 1,
   "Battleaxe + Holy Staff": 1
  },
  "Holy Staff + Prowling Staff": {
   "Brawler Gloves + Brawler Gloves": 1,
   "Bow of Badon + Holy Staff": 2,
   "Holy Staff + Kingmaker": 2,
   "Heavy Crossbow + Holy Staff": 1,
   "Fists of Avalon + Staff of Balance": 1,
   "Demonic Staff + Holy Staff": 2,
   "Carving Sword + Longbow": 1,
   "Claymore + Holy Staff": 3,
   "Arclight Blasters + Holy Staff": 3,
   "Cursed Staff + Holy Staff": 1,
   "Glaive + Holy Staff": 2,
   "Dagger Pair + Holy Staff": 1,
   "Great Holy Staff + Hellspawn Staff": 2,
   "Carving Sword + Holy Staff": 1,
   "Claymore + Wildfire Staff": 1
  },
  "Brawler Gloves + Brawler Gloves": {
   "Carving Sword + Holy Staff": 1,
   "Black Monk Stave + Dagger": 1,
   "Fists of Avalon + Holy Staff": 1,
   "Claymore + Great Holy Staff": 1,
   "Claymore + Holy Staff": 4,
   "Bow of Badon + Greataxe": 1,
   "Carrioncaller + Holy Staff": 1,
   "Hellspawn Staff + Holy Staff": 1,
   "Dagger + Tombhammer": 1
  },
  "Crystal Reaper + Holy Staff": {
   "Mistpiercer + Mistpiercer": 1,
   "Battleaxe + Holy Staff": 1,
   "Warbow + Warbow": 1,
   "Holy Staff + Twin Slayers": 1,
   "Bow of Badon + Greataxe": 1,
   "Blazing Staff + Tombhammer": 1
  },
  "Demonic Staff + Ironroot Staff": {
   "Great Holy Staff + Prowling Staff": 1,
   "Realmbreaker + Soulscythe": 2
  },
  "Bow of Badon + Brawler Gloves": {
   "Demonic Staff + Longbow": 1
  },
  "Brawler Gloves + Warbow": {
   "Cursed Staff + Holy Staff": 1
  },
  "Dagger + Staff of Balance": {
   "Fists of Avalon + Holy Staff": 1,
   "Dagger Pair + Heavy Crossbow": 1,
   "Dagger Pair + Holy Staff": 2,
   "Heavy Crossbow + Holy Staff": 1
  },
  "Carving Sword + Hallowfall": {
   "Battleaxe + Ursine Maulers": 1
  },
  "Warbow + Warbow": {
   "Bow of Badon + Mistpiercer": 1,
   "Holy Staff + Kingmaker": 1,
   "Heavy Crossbow + Heavy Crossbow": 1,
   "Bloodletter + Realmbreaker": 1,
   "Fists of Avalon + Soulscythe": 1,
   "Energy Shaper + Soulscythe": 1,
   "Wildfire Staff + Wildfire Staff": 2
  },
  "Dagger Pair + Ironroot Staff": {
   "Claymore + Holy Staff": 2,
   "Brawler Gloves + Brawler Gloves": 2,
   "Brawler Gloves + Heron Spear": 1,
   "Demonic Staff + Holy Staff": 1,
   "Hellspawn Staff + Holy Staff": 1
  },
  "Brawler Gloves + Dagger": {
   "Cursed Staff + Hallowfall": 1
  },
  "Holy Staff + Wildfire Staff": {
   "Heavy Crossbow + Heavy Crossbow": 1
  },
  "Heavy Crossbow + Heavy Crossbow": {
   "Deathgivers + Holy Staff": 1,
   "Bear Paws + Claymore": 1
  },
  "Hellfire Hands + Holy Staff": {
   "Heavy Crossbow + Holy Staff": 1,
   "Warbow + Warbow": 1,
   "Brawler Gloves + Dagger Pair": 1,
   "Hellspawn Staff + Holy Staff": 2,
   "Claymore + Holy Staff": 3,
   "Carving Sword + Holy Staff": 2,
   "Demonic Staff + Great Holy Staff": 1,
   "Brawler Gloves + Tombhammer": 1,
   "Crystal Reaper + Hallowfall": 1,
   "Grailseeker + Holy Staff": 1,
   "Demonic Staff + Holy Staff": 1
  },
  "Broadsword + Ironroot Staff": {
   "Blight Staff + Greataxe": 1
  },
  "Fists of Avalon + Holy Staff": {
   "Claymore + Holy Staff": 3,
   "Demonic Staff + Holy Staff": 3,
   "Heavy Crossbow + Holy Staff": 1,
   "Bloodletter + Whispering Bow": 1,
   "Dagger + Staff of Balance": 1,
   "Hellspawn Staff + Holy Staff": 1,
   "Bear Paws + Holy Staff": 1,
   "Battleaxe + Holy Staff": 1,
   "Carving Sword + Holy Staff": 1,
   "Dagger Pair + Holy Staff": 1,
   "Dagger Pair + Great Holy Staff": 1,
   "Holy Staff + Tombhammer": 1,
   "Realmbreaker + Soulscythe": 1
  },
  "Hellfire Hands + Tombhammer": {
   "Fists of Avalon + Holy Staff": 1,
   "Black Monk Stave + Deathgivers": 1,
   "Heavy Crossbow + Holy Staff": 1,
   "Heavy Crossbow + Tombhammer": 1,
   "Brawler Gloves + Holy Staff": 1,
   "Claymore + Ironroot Staff": 1,
   "Hellspawn Staff + Holy Staff": 1,
   "Bloodletter + Crossbow": 1,
   "Dagger Pair + Holy Staff": 1
  },
  "Battleaxe + Demonic Staff": {
   "Great Fire Staff + Greataxe": 1
  },
  "Battleaxe + Cursed Staff": {
   "Battleaxe + Battleaxe": 1
  },
  "Bear Paws + Bow of Badon": {
   "Bow of Badon + Holy Staff": 1,
   "Bow of Badon + Claymore": 1
  },
  "Carrioncaller + Heavy Crossbow": {
   "Cursed Staff + Holy Staff": 1,
   "Bloodletter + Heavy Crossbow": 1,
   "Dagger Pair + Holy Staff": 1
  },
  "Heavy Crossbow + Prowling Staff": {
   "Black Monk Stave + Dagger": 1,
   "Dagger Pair + Glaive": 1,
   "Claymore + Heavy Crossbow": 1
  },
  "Black Monk Stave + Dagger": {
   "Battleaxe + Heron Spear": 1
  },
  "Heavy Crossbow + Warbow": {
   "Heavy Crossbow + Holy Staff": 1
  },
  "Bloodletter + Pike": {
   "Heavy Crossbow + Holy Staff": 1
  },
  "Spirithunter + Tombhammer": {
   "Dagger + Grailseeker": 1
  },
  "Bear Paws + Longbow": {
   "Longbow + Pike": 1
  },
  "Claymore + Hallowfall": {
   "Hellspawn Staff + Holy Staff": 1,
   "Claymore + Holy Staff": 2,
   "Bow of Badon + Crystal Reaper": 1
  },
  "Battleaxe + Bear Paws": {
   "Bloodletter + Greataxe": 1,
   "Bear Paws + Cursed Staff": 1
  },
  "Bear Paws + Bear Paws": {
   "Battleaxe + Greataxe": 1
  },
  "Greataxe + Warbow": {
   "Longbow + Warbow": 1
  },
  "Hallowfall + Hellspawn Staff": {
   "Dawnsong + Energy Shaper": 1
  },
  "Greataxe + Heron Spear": {
   "Glacial Staff + Staff of Balance": 1
  },
  "Broadsword + Holy Staff": {
   "Bow of Badon + Holy Staff": 1,
   "Ironroot Staff + Kingmaker": 1,
   "Deathgivers + Holy Staff": 1,
   "Dagger Pair + Dagger Pair": 1,
   "Greataxe + Holy Staff": 1,
   "Claymore + Holy Staff": 1
  },
  "Bow of Badon + Crystal Reaper": {
   "Bow of Badon + Longbow": 1
  },
  "Crystal Reaper + Heron Spear": {
   "Energy Shaper + Heron Spear": 1
  },
  "Arclight Blasters + Bloodletter": {
   "Bow of Badon + Hallowfall": 1
  },
  "Bloodletter + Carrioncaller": {
   "Claymore + Holy Staff": 1
  },
  "Fists of Avalon + Ironroot Staff": {
   "Battleaxe + Holy Staff": 1
  },
  "Carving Sword + Heavy Crossbow": {
   "Heavy Crossbow + Prowling Staff": 1,
   "Claymore + Holy Staff": 1
  },
  "Dagger Pair + Heavy Crossbow": {
   "Glacial Staff + Staff of Balance": 1,
   "Grailseeker + Realmbreaker": 1
  },
  "Holy Staff + Realmbreaker": {
   "Bow of Badon + Holy Staff": 1
  },
  "Realmbreaker + Redemption Staff": {
   "Battleaxe + Claymore": 1
  },
  "Carving Sword + Hellspawn Staff": {
   "Arclight Blasters + Crystal Reaper": 1
  },
  "Glacial Staff + Staff of Balance": {
   "Bear Paws + Whispering Bow": 1,
   "Heavy Crossbow + Holy Staff": 2,
   "Crystal Reaper + Great Holy Staff": 1,
   "Glaive + Holy Staff": 1,
   "Battleaxe + Wildfire Staff": 1,
   "Hellspawn Staff + Holy Staff": 3,
   "Claymore + Holy Staff": 2,
   "Demonic Staff + Holy Staff": 1,
   "Fists of Avalon + Holy Staff": 1,
   "Dagger Pair + Holy Staff": 1,
   "Great Holy Staff + Prowling Staff": 1,
   "Warbow + Wildfire Staff": 1,
   "Carving Sword + Holy Staff": 1
  },
  "Dagger Pair + Dagger Pair": {
   "Dagger Pair + Soulscythe": 1,
   "Longbow + Longbow": 1,
   "Claymore + Holy Staff": 2,
   "Dagger Pair + Holy Staff": 1,
   "Battleaxe + Hallowfall": 1,
   "Cursed Staff + Holy Staff": 1,
   "Bloodletter + Holy Staff": 1
  },
  "Grailseeker + Heron Spear": {
   "Great Fire Staff + Greataxe": 1
  },
  "Claymore + Great Holy Staff": {
   "Grailseeker + Great Fire Staff": 1,
   "Battleaxe + Holy Staff": 1
  },
  "Bloodletter + Hellspawn Staff": {
   "Arclight Blasters + Cursed Staff": 1
  },
  "Great Fire Staff + Holy Staff": {
   "Dagger Pair + Dagger Pair": 1,
   "Blazing Staff + Twin Slayers": 1
  },
  "Glaive + Holy Staff": {
   "Claymore + Holy Staff": 6,
   "Dagger Pair + Holy Staff": 2,
   "Heavy Crossbow + Holy Staff": 2,
   "Demonic Staff + Holy Staff": 2,
   "Arclight Blasters + Holy Staff": 3,
   "Glaive + Holy Staff": 1,
   "Carrioncaller + Holy Staff": 2,
   "Holy Staff + Prowling Staff": 1,
   "Bear Paws + Dagger Pair": 1
  },
  "Claymore + Heavy Crossbow": {
   "Glaive + Holy Staff": 1,
   "Hellspawn Staff + Holy Staff": 1,
   "Carving Sword + Holy Staff": 1,
   "Black Monk Stave + Crossbow": 1,
   "Dagger Pair + Holy Staff": 1
  },
  "Staff of Balance + Wildfire Staff": {
   "Claymore + Holy Staff": 1
  },
  "Arclight Blasters + Mistpiercer": {
   "Grailseeker + Longbow": 1
  },
  "Holy Staff + Longbow": {
   "Infernal Scythe + Redemption Staff": 1
  },
  "Brawler Gloves + Longbow": {
   "Infernal Scythe + Staff of Balance": 1
  },
  "Energy Shaper + Greataxe": {
   "Bow of Badon + Energy Shaper": 1,
   "Holy Staff + Kingmaker": 1
  },
  "Dagger Pair + Soulscythe": {
   "Bedrock Mace + Glacial Staff": 1,
   "Heavy Crossbow + Holy Staff": 1
  },
  "Battleaxe + Bow of Badon": {
   "Bear Paws + Whispering Bow": 1,
   "Dagger Pair + Holy Staff": 1
  },
  "Bear Paws + Dagger Pair": {
   "Cursed Staff + Longbow": 1
  },
  "Arclight Blasters + Ironroot Staff": {
   "Carving Sword + Holy Staff": 1
  },
  "Bloodletter + Bow of Badon": {
   "Claymore + Deathgivers": 1,
   "Bow of Badon + Ursine Maulers": 1
  },
  "Holy Staff + Pike": {
   "Hellspawn Staff + Holy Staff": 1,
   "Dagger Pair + Deathgivers": 1,
   "Claymore + Holy Staff": 2
  },
  "Dagger Pair + Greataxe": {
   "Heavy Crossbow + Holy Staff": 1
  },
  "Holy Staff + Lifecurse Staff": {
   "Battleaxe + Holy Staff": 1,
   "Dagger + Staff of Balance": 1,
   "Dagger Pair + Hellfire Hands": 2,
   "Tombhammer + Whispering Bow": 1,
   "Warbow + Warbow": 2,
   "Claymore + Holy Staff": 2
  },
  "Crossbow + Holy Staff": {
   "Claymore + Holy Staff": 1,
   "Fists of Avalon + Heron Spear": 1,
   "Great Fire Staff + Holy Staff": 2
  },
  "Greataxe + Hellfire Hands": {
   "Holy Staff + Infernal Scythe": 1,
   "Dagger Pair + Grailseeker": 1
  },
  "Battleaxe + Tombhammer": {
   "Bear Paws + Dagger Pair": 1,
   "Dagger Pair + Holy Staff": 1
  },
  "Hellspawn Staff + Redemption Staff": {
   "Energy Shaper + Grailseeker": 1
  },
  "Arclight Blasters + Kingmaker": {
   "Heavy Crossbow + Holy Staff": 1,
   "Bow of Badon + Holy Staff": 1,
   "Bear Paws + Blazing Staff": 1
  },
  "Longbow + Tombhammer": {
   "Bear Paws + Blazing Staff": 1,
   "Bow of Badon + Daybreaker": 1
  },
  "Bow of Badon + Tombhammer": {
   "Warbow + Warbow": 1,
   "Infernal Scythe + Realmbreaker": 1,
   "Bear Paws + Infernal Scythe": 1,
   "Bow of Badon + Holy Staff": 1
  },
  "Fists of Avalon + Staff of Balance": {
   "Claymore + Holy Staff": 1,
   "Hellfire Hands + Holy Staff": 1
  },
  "Brawler Gloves + Heavy Crossbow": {
   "Hellspawn Staff + Holy Staff": 1
  },
  "Brawler Gloves + Tombhammer": {
   "Demonic Staff + Holy Staff": 1,
   "Carrioncaller + Holy Staff": 1,
   "Dagger Pair + Greataxe": 1
  },
  "Brawler Gloves + Heron Spear": {
   "Demonic Staff + Holy Staff": 1,
   "Dagger Pair + Great Holy Staff": 2,
   "Claymore + Holy Staff": 3,
   "Dagger Pair + Dagger Pair": 1,
   "Warbow + Warbow": 1,
   "Battleaxe + Holy Staff": 1,
   "Dagger Pair + Holy Staff": 2,
   "Bloodletter + Crossbow": 1
  },
  "Battleaxe + Fists of Avalon": {
   "Broadsword + Wildfire Staff": 1
  },
  "Carving Sword + Warbow": {
   "Dagger Pair + Dagger Pair": 1
  },
  "Dagger + Energy Shaper": {
   "Holy Staff + Kingmaker": 1
  },
  "Claymore + Dagger Pair": {
   "Cursed Staff + Rotcaller Staff": 1
  },
  "Dagger Pair + Great Holy Staff": {
   "Battleaxe + Bow of Badon": 1,
   "Glacial Staff + Staff of Balance": 1,
   "Claymore + Holy Staff": 2,
   "Great Holy Staff + Heavy Crossbow": 1,
   "Greataxe + Holy Staff": 3,
   "Bow of Badon + Greataxe": 1
  },
  "Bow of Badon + Heron Spear": {
   "Claymore + Dagger Pair": 1,
   "Dagger + Greataxe": 1
  },
  "Bear Paws + Bloodletter": {
   "Battleaxe + Warbow": 1
  },
  "Fists of Avalon + Soulscythe": {
   "Bloodletter + Hellfire Hands": 1
  },
  "Blazing Staff + Staff of Balance": {
   "Heavy Crossbow + Holy Staff": 1
  },
  "Holy Staff + Mistpiercer": {
   "Dagger Pair + Dagger Pair": 1
  },
  "Crystal Reaper + Hallowfall": {
   "Heron Spear + Holy Staff": 1,
   "Bear Paws + Infernal Scythe": 1
  },
  "Broadsword + Great Holy Staff": {
   "Hellfire Hands + Holy Staff": 1
  },
  "Crossbow + Greataxe": {
   "Carving Sword + Hallowfall": 1
  },
  "Cursed Staff + Redemption Staff": {
   "Dagger + Heron Spear": 1
  },
  "Bear Paws + Blazing Staff": {
   "Bow of Badon + Brawler Gloves": 1
  },
  "Carving Sword + Longbow": {
   "Blazing Staff + Energy Shaper": 1
  },
  "Bear Paws + Great Holy Staff": {
   "Bear Paws + Longbow": 1
  },
  "Bloodletter + Tombhammer": {
   "Claymore + Holy Staff": 1
  },
  "Crystal Reaper + Longbow": {
   "Claymore + Greataxe": 1
  },
  "Hellspawn Staff + Mistpiercer": {
   "Carving Sword + Holy Staff": 1,
   "Hellfire Hands + Holy Staff": 1
  },
  "Arclight Blasters + Great Holy Staff": {
   "Arclight Blasters + Holy Staff": 3,
   "Claymore + Holy Staff": 1,
   "Demonic Staff + Holy Staff": 2,
   "Holy Staff + Lifecurse Staff": 1,
   "Warbow + Warbow": 1,
   "Hellspawn Staff + Holy Staff": 3,
   "Great Holy Staff + Heavy Crossbow": 1,
   "Holy Staff + Rotcaller Staff": 2,
   "Deathgivers + Holy Staff": 1
  },
  "Daybreaker + Holy Staff": {
   "Bear Paws + Holy Staff": 1,
   "Longbow + Redemption Staff": 1
  },
  "Bear Paws + Hellfire Hands": {
   "Bow of Badon + Holy Staff": 1
  },
  "Bloodletter + Heron Spear": {
   "Claymore + Dagger Pair": 1
  },
  "Bow of Badon + Dagger Pair": {
   "Bear Paws + Bow of Badon": 1
  },
  "Heavy Crossbow + Heron Spear": {
   "Deathgivers + Holy Staff": 1,
   "Dagger Pair + Divine Staff": 1
  },
  "Bear Paws + Fists of Avalon": {
   "Brawler Gloves + Cursed Staff": 1,
   "Battleaxe + Tombhammer": 1
  },
  "Bear Paws + Dawnsong": {
   "Dawnsong + Greataxe": 1
  },
  "Battleaxe + Deathgivers": {
   "Carving Sword + Claymore": 1
  },
  "Dagger Pair + Grailseeker": {
   "Dagger Pair + Lifecurse Staff": 1
  },
  "Fists of Avalon + Heavy Crossbow": {
   "Bear Paws + Holy Staff": 1
  },
  "Heron Spear + Holy Staff": {
   "Greataxe + Tombhammer": 1,
   "Crossbow + Spirithunter": 1
  },
  "Fists of Avalon + Warbow": {
   "Bow of Badon + Dagger Pair": 2
  },
  "Carving Sword + Great Holy Staff": {
   "Arclight Blasters + Holy Staff": 1,
   "Carving Sword + Holy Staff": 1
  },
  "Heavy Crossbow + Tombhammer": {
   "Hellfire Hands + Tombhammer": 5,
   "Demonic Staff + Tombhammer": 1,
   "Battleaxe + Holy Staff": 1
  },
  "Glaive + Great Holy Staff": {
   "Holy Staff + Lifecurse Staff": 1,
   "Claymore + Holy Staff": 1
  },
  "Great Holy Staff + Hellspawn Staff": {
   "Arclight Blasters + Holy Staff": 1
  },
  "Blight Staff + Longbow": {
   "Longbow + Longbow": 1
  },
  "Dagger Pair + Hellfire Hands": {
   "Hellfire Hands + Longbow": 1
  },
  "Claymore + Greataxe": {
   "Dagger Pair + Tombhammer": 1
  },
  "Carrioncaller + Hallowfall": {
   "Bow of Badon + Holy Staff": 1
  },
  "Energy Shaper + Soulscythe": {
   "Heavy Crossbow + Holy Staff": 1,
   "Bow of Badon + Holy Staff": 1,
   "Claymore + Holy Staff": 1,
   "Demonic Staff + Holy Staff": 1
  },
  "Dagger + Tombhammer": {
   "Carving Sword + Holy Staff": 1,
   "Claymore + Holy Staff": 1
  },
  "Brawler Gloves + Holy Staff": {
   "Battleaxe + Hallowfall": 1,
   "Dagger + Grailseeker": 1,
   "Brawler Gloves + Ursine Maulers": 1,
   "Hellspawn Staff + Holy Staff": 1,
   "Hellfire Hands + Tombhammer": 1
  },
  "Hellspawn Staff + Longbow": {
   "Fists of Avalon + Realmbreaker": 1
  },
  "Dawnsong + Holy Staff": {
   "Bear Paws + Holy Staff": 1
  },
  "Fists of Avalon + Mistpiercer": {
   "Cursed Staff + Holy Staff": 1
  },
  "Battleaxe + Hallowfall": {
   "Claymore + Holy Staff": 1,
   "Brawler Gloves + Brawler Gloves": 1,
   "Longbow + Tombhammer": 1
  },
  "Demonic Staff + Redemption Staff": {
   "Battleaxe + Hallowfall": 1
  },
  "Bear Paws + Hellspawn Staff": {
   "Battleaxe + Bear Paws": 1
  },
  "Hellspawn Staff + Twin Slayers": {
   "Greataxe + Warbow": 1
  },
  "Heron Spear + Mistpiercer": {
   "Greataxe + Holy Staff": 1,
   "Hellfire Hands + Hellspawn Staff": 1,
   "Longbow + Twin Slayers": 1,
   "Blazing Staff + Grailseeker": 1
  },
  "Crystal Reaper + Redemption Staff": {
   "Claymore + Holy Staff": 1
  },
  "Hallowfall + Heron Spear": {
   "Dawnsong + Mistpiercer": 1
  },
  "Holy Staff + Infernal Scythe": {
   "Carving Sword + Redemption Staff": 1
  },
  "Pike + Whispering Bow": {
   "Cursed Staff + Dagger Pair": 1
  },
  "Tombhammer + Whispering Bow": {
   "Brawler Gloves + Dagger Pair": 1,
   "Carrioncaller + Dagger Pair": 1
  },
  "Heavy Crossbow + Whispering Bow": {
   "Brawler Gloves + Crossbow": 1,
   "Hellfire Hands + Mistpiercer": 1
  },
  "Arclight Blasters + Bear Paws": {
   "Bow of Badon + Dawnsong": 1
  },
  "Dagger Pair + Ursine Maulers": {
   "Kingmaker + Longbow": 1
  },
  "Dagger Pair + Tombhammer": {
   "Greataxe + Staff of Balance": 1,
   "Hellspawn Staff + Holy Staff": 1
  },
  "Fists of Avalon + Hellspawn Staff": {
   "Hellspawn Staff + Holy Staff": 1
  },
  "Bear Paws + Redemption Staff": {
   "Dagger Pair + Ursine Maulers": 1
  },
  "Cursed Staff + Lifecurse Staff": {
   "Bow of Badon + Heavy Crossbow": 1
  },
  "Deathgivers + Heavy Crossbow": {
   "Blazing Staff + Heavy Crossbow": 1
  },
  "Bow of Badon + Staff of Balance": {
   "Claymore + Holy Staff": 1
  },
  "Bow of Badon + Kingmaker": {
   "Heron Spear + Mistpiercer": 1
  },
  "Bear Paws + Infernal Scythe": {
   "Dagger + Grailseeker": 1
  },
  "Bow of Badon + Claymore": {
   "Dagger + Grailseeker": 1
  },
  "Great Holy Staff + Heavy Crossbow": {
   "Demonic Staff + Holy Staff": 1,
   "Claymore + Holy Staff": 1,
   "Greataxe + Holy Staff": 1
  },
  "Fists of Avalon + Greataxe": {
   "Daybreaker + Holy Staff": 1
  },
  "Realmbreaker + Soulscythe": {
   "Claymore + Holy Staff": 1,
   "Deathgivers + Holy Staff": 1,
   "Holy Staff + Kingmaker": 1,
   "Dagger Pair + Soulscythe": 1,
   "Heavy Crossbow + Holy Staff": 1
  },
  "Greataxe + Kingmaker": {
   "Hallowfall + Heavy Crossbow": 1
  },
  "Heavy Crossbow + Ironroot Staff": {
   "Crossbow + Holy Staff": 1
  },
  "Arclight Blasters + Rotcaller Staff": {
   "Arclight Blasters + Staff of Balance": 1
  },
  "Carving Sword + Whispering Bow": {
   "Bow of Badon + Staff of Balance": 1
  },
  "Hellspawn Staff + Ironroot Staff": {
   "Hellspawn Staff + Holy Staff": 1
  },
  "Bow of Badon + Greataxe": {
   "Dagger Pair + Holy Staff": 1
  },
  "Great Holy Staff + Greataxe": {
   "Bloodletter + Heron Spear": 1,
   "Fists of Avalon + Fists of Avalon": 1
  },
  "Bow of Badon + Hellspawn Staff": {
   "Greataxe + Hallowfall": 1
  },
  "Carrioncaller + Ironroot Staff": {
   "Bloodletter + Holy Staff": 1,
   "Fists of Avalon + Holy Staff": 1
  },
  "Great Arcane Staff + Hellfire Hands": {
   "Battleaxe + Holy Staff": 2,
   "Carrioncaller + Ironroot Staff": 1,
   "Greataxe + Holy Staff": 1,
   "Dagger Pair + Holy Staff": 2,
   "Carrioncaller + Holy Staff": 2
  },
  "Arclight Blasters + Staff of Balance": {
   "Great Holy Staff + Greataxe": 1
  },
  "Bow of Badon + Great Holy Staff": {
   "Bow of Badon + Great Holy Staff": 1,
   "Greataxe + Greataxe": 1
  },
  "Demonic Staff + Great Holy Staff": {
   "Realmbreaker + Soulscythe": 2
  },
  "Crystal Reaper + Divine Staff": {
   "Greataxe + Holy Staff": 1
  },
  "Grailseeker + Realmbreaker": {
   "Claymore + Holy Staff": 1
  },
  "Carrioncaller + Great Holy Staff": {
   "Holy Staff + Kingmaker": 1
  },
  "Dagger Pair + Great Arcane Staff": {
   "Fists of Avalon + Holy Staff": 1,
   "Holy Staff + Kingmaker": 1
  }
 }
};
